### ISSUE TITLE
[Loopring 3.5]: Offchain deposit

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1036]
Should we enable **offchain deposit**, so users sign offchain deposit requests to us, then we use the ERC20 allowance to transfer up to their requested amount of tokens **in a batch** tx to the exchange. The circuits should be the same.

The offchain deposit request won't work for Ether.

The offchain deposit will have a short expiry such as 3 hours.

## Benefits:
- Users can cancel the deposit offchain deposit at no cost, and most deposits will be handled in batches so the settlement circuits can handle larger blocks more often without being interrupted by many onchain deposits/withdrawals.

**Comment by Brechtpd** [comment]
I think this would be a good idea. This will be very easy to implement using Agents as this is exactly the type of functionality this was made for i.e. doing operations for users using smart contract logic. So this would just be a simple contract that checks user signatures for the deposits and does the actual deposit for the user.

> Settlement circuits can handle larger blocks more often without being interrupted by many onchain deposits/withdrawals.

There's already a lot flexibility when these onchain requests need to be handled, so I don't think the offchain requests provide any more flexibility as in essence it's just an offchain request that's stored onchain with a time limit when it needs to processed (which will always be quite long and will almost always be handled much sooner for user experience reasons).

**Comment by Brechtpd** [comment]
For withdrawals it's a good idea in any case to switch to offchain withdrawal requests because it will save users the gas cost for doing the request onchain (which is really only there for security reasons).

**Comment by Brechtpd** [comment]
> Settlement circuits can handle larger blocks more often without being interrupted by many onchain deposits/withdrawals.

I think there's never any reason deposits need to interrupt trades. There is just extra balance in the account after a deposit so this has no impact on trades that already happened before. The deposit can always be made available to users immediately once it's onchain (+ some confirmations so the deposit isn't reorged out). The only thing the relayer may need to do is submit the deposit block before any settlement block that's currently being constructed (as trades after the deposit happened may use the extra balance). Users don't even see any impact on postponing any deposit block as the deposited amount is made available for trading immediately even if the deposit isn't yet included in a block. So the relayer can wait on committing these deposit blocks and settlement blocks pretty much indefinitely until they are big enough.

Withdrawals however are a bit more difficult as they can actually use a balance that's only available after a trade. But even that shouldn't be that much of a problem. Once a user does a withdrawal the balance that gets withdrawn is simply made unavailable for trading. The blocks of the different block types can keep on being built for some time until the withdrawal really needs to be done (either the blocks are big enough or the max time for doing the withdrawal needs to be done). Withdrawal blocks need to be submitted after any settlement blocks if there is indeed a dependency on either a deposit or trade.

So with method described above I think we don't need to commit many blocks in any case because we can build the deposit, settlement and withdraw blocks in parallel for as long as needed (or wanted) because any dependencies can easily be solved. The only general rule is that the blocks need to be submitted in the order Deposit blocks - Settlement blocks - Withdrawal blocks.

So if there are a couple of deposits and withdraws in an hour we should always be able to commit blocks like this:

1x Deposit block - Nx Settlement blocks - 1x Withdraw block

And with a max withdrawal time of 40 minutes we also have 40 minutes to fill Deposit blocks and 40 minutes to fill Settlement blocks. This should be okay I think even if there aren't many requests.

**Comment by hosschao** [comment]
> > Settlement circuits can handle larger blocks more often without being interrupted by many onchain deposits/withdrawals.
> 
> I think there's never any reason deposits/withdrawals need to interrupt trades. There is just extra balance in the account after a deposit so this has no impact on trades that already happened before even when doing the deposit before those trades. The deposit can always be made available to users immediately once the deposit was done onchain by the user (+ some confirmations so the deposit to the exchange isn't re-orged out), it doesn't have to be included in a block for that. The only thing the relayer may need to do is submit the deposit block before any settlement block that's currently being constructed (as trades after the deposit happened may use the extra balance). Changing the trading key is an exception but that shouldn't happen much (and this is only a problem when there is also a dependency) and could be solved at the UI level (or even the relayer level by tracking this dependency and adding it to the correct block). Users don't even see any impact on postponing any deposit block as the deposited amount is made available for trading immediately even if the deposit isn't yet included in a block. So the relayer can wait on committing these deposit blocks and settlement blocks pretty much indefinitely until they are big enough.
> 
> Withdrawals are a bit more difficult as they can actually use a balance that's only available after a trade. But even that shouldn't be that much of a problem. Once a user does a withdrawal the balance that gets withdrawn is simply made unavailable for trading. The blocks of the different block types can keep on being built for some time until the withdrawal really needs to be done (either the blocks are big enough or the max time for doing the withdrawal needs to be done). Withdrawal blocks need to be submitted after any settlement blocks if there is indeed a dependency on either a deposit or trade.
> 
> So with the method described above I think we don't need to commit many blocks in any case because we can build the deposit, settlement and withdraw blocks in parallel for as long as needed (or wanted) because any dependencies can easily be solved. The only general rule is that the blocks need to be submitted in the order Deposit blocks - Settlement blocks - Withdrawal blocks.
> 
> So if there are only a couple of deposits and withdrawals in an hour we should always be able to commit blocks like this:
> 
> 1x Deposit block - Nx Settlement blocks (one big block or more if > 1024 trades) - 1x Withdraw block
We did almost the same thing: During blocking phase, rearrange the txs and make all deposit at head, rings in middle and withdraw txs at end.
The reasons why we don't have enough 'big' blocks are:
1. Change password request will split the trade blocks. Just as you mentioned, it's not happened so often.
2. The major reason is we want process withdraw request as soon as possible. So we didn't wait 40 min and only 5 min for now. Currently we use aws batch job to do proving generation stuff. It will take 20 mins(we are solving this problem). So even we only wait 5 mins, user still need wait almost 40mins(30 confirmation + 20 min + 5 min + 5 min) The last 5 mins is waiting for batch validation. 5 min waiting is the reason we don't have enough txs in a block.

One more thing, we have 1/3 over-amount withdraw currently, which means users withdraw higher amount than they have. This is a complex case we need handle carefully. It will miss our account balance if we miss the order of over-amount withdraw request and related ring request. And it will become a different story if we put following ring txs before previous over-amount withdraw request.

So the actual case is much more complex than this one ^_^:
1x Deposit block - Nx Settlement blocks (one big block or more if > 1024 trades) - 1x Withdraw block

> 
> And with a max withdrawal time of 40 minutes we also have 40 minutes to fill Deposit blocks and 40 minutes to fill Settlement blocks. This should be okay I think even if there aren't many requests. In the worst case with very few requests we need to commit < 100 blocks per day in total and still do all withdrawals in less than 40 minutes. Note that with fast withdrawals we don't even have this self-imposed time limit and we can only submit blocks when they are big enough (or we want to recoup funds used by the fast withdrawals).

**Comment by Brechtpd** [comment]
>  1. Change password request will split the trade blocks. Just as you mentioned, it's not happened so often.
>  2. The major reason is we want process withdraw request as soon as possible. So we didn't wait 40 min and only 5 min for now. Currently we use aws batch job to do proving generation stuff. It will take 20 mins(we are solving this problem). So even we only wait 5 mins, user still need wait almost 40mins(30 confirmation + 20 min + 5 min + 5 min) The last 5 mins is waiting for batch validation. 5 min waiting is the reason we don't have enough txs in a block.

Ah, I didn't know the proof generation was that big of a part currently.

> The last 5 mins is waiting for batch validation.

Could you explain this a bit more?

> One more thing, we have 1/3 over-amount withdraw currently, which means users withdraw higher amount than they have. This is a complex case we need handle carefully. It will miss our account balance if we miss the order of over-amount withdraw request and related ring request. And it will become a different story if we put following ring txs before previous over-amount withdraw request.

I see, I didn't think of this. Though in that case I'd say the actual amount withdrawn doesn't need to match the amount at withdrawal time (whichever time that is as you could choose different times for that i.e. when the transaction is created vs when the transaction is included), but I can see how that makes it more difficult for the relayer to track the actual balance in the account. I'd say this should still be handled by making the complete amount unavailable for trading and if there is an extra balance because the user has bought more after doing the withdrawal request than that can also be used in the withdrawal in this special case. Is this currently handled by splitting up the settlement blocks?

But this is even more reason to completely switch from onchain withdrawal requests to offchain withdrawal requests because then the withdrawal can simply be denied in the UI when this over-amount case happens as it can be checked against the actual amount available at submission time. (And offchain withrawal requests have other benefits as well).

> So the actual case is much more complex than this one ^_^:
> 1x Deposit block - Nx Settlement blocks (one big block or more if > 1024 trades) - 1x Withdraw block

Still not too bad I think! I simplified it to only the dependencies between blocks, and it seems that the different request types aren't too much of a problem in practice (or at least there are solutions for it). Even for the password reset case there are acceptable simple solutions like stopping the user from trading for X minutes until the (Deposit/Settlement/Withdraw) blocks are submitted that handle the reset and a new set of (Deposit/Settlement/Withdraw) blocks are started.

Thanks for the explanation. :)

**Comment by hosschao** [comment]
> > 1. Change password request will split the trade blocks. Just as you mentioned, it's not happened so often.
> > 2. The major reason is we want process withdraw request as soon as possible. So we didn't wait 40 min and only 5 min for now. Currently we use aws batch job to do proving generation stuff. It will take 20 mins(we are solving this problem). So even we only wait 5 mins, user still need wait almost 40mins(30 confirmation + 20 min + 5 min + 5 min) The last 5 mins is waiting for batch validation. 5 min waiting is the reason we don't have enough txs in a block.
> 
> Ah, I didn't know the proof generation was that big of a part currently.
> 
> > The last 5 mins is waiting for batch validation.
> 
> Could you explain this a bit more?
In order to save the cost. Currently solution is submit verification in a batch. So we can use only one tx to submit several verifications.
> 
> > One more thing, we have 1/3 over-amount withdraw currently, which means users withdraw higher amount than they have. This is a complex case we need handle carefully. It will miss our account balance if we miss the order of over-amount withdraw request and related ring request. And it will become a different story if we put following ring txs before previous over-amount withdraw request.
> 
> I see, I didn't think of this. Though in that case I'd say the actual amount withdrawn doesn't need to match the amount at withdrawal time (whichever time that is as you could choose different times for that i.e. when the transaction is created vs when the transaction is included), but I can see how that makes it more difficult for the relayer to track the actual balance in the account. I'd say this should still be handled by making the complete amount unavailable for trading and if there is an extra balance because the user has bought more after doing the withdrawal request than that can also be used in the withdrawal in this special case. Is this currently handled by splitting up the settlement blocks?
> 
> But this is even more reason to completely switch from onchain withdrawal requests to offchain withdrawal requests because then the withdrawal can simply be denied in the UI when this over-amount case happens as it can be checked against the actual amount available at submission time. (And offchain withrawal requests have other benefits as well).
> 
> > So the actual case is much more complex than this one ^_^:
> > 1x Deposit block - Nx Settlement blocks (one big block or more if > 1024 trades) - 1x Withdraw block
> 
> Still not too bad I think! I simplified it to only the dependencies between blocks, and it seems that the different request types aren't too much of a problem in practice (or at least there are solutions for it). Even for the password reset case there are acceptable simple solutions like stopping the user from trading for X minutes until the (Deposit/Settlement/Withdraw) blocks are submitted that handle the reset and a new set of (Deposit/Settlement/Withdraw) blocks are started.
> 
> Thanks for the explanation. :)

**Comment by dong77** [comment]
see [[Loopring 3.5] Loopring 3.5 New Features and Changes ](https://github.com/Loopring/protocols/issues/1034)
