### ISSUE TITLE
[Hebao]lock issue of LockModule

### ISSUE THREAD

**Issue by adamchen0510** [Loopring/protocols#1085]
When guardian is contract wallet but no EOA, the lock would happen signature issue.
It caused by extractMetaTxSigners in LockModule.sol, it directly return the guardian as signer.
If the guardian is an EOS address, it would be fine,
if the guardian is a contract wallet address, it need return the owner of the wallet.
![image](https://user-images.githubusercontent.com/13066091/79227047-ed035e00-7e91-11ea-8913-f3b0a927fc55.png)

**Comment by Brechtpd** [comment]
As long as the guardian contract implements ERC1271 this isn't a problem. `isValidSignature` signature will be called on the contract to check the signature if the `WALLET` signature type is used.

The way this works for our wallet (using `ERC1271Module`) is pretty simple because of the way our signatures work. The type of the signature is stored in the last byte. The guardian wallet owner will have to sign the data like you'd expect. If for example EIP712 is used to sign the data the signature sent onchain would look like this if the guardian is an EOA: 
```
signatureData | SignatureType.EIP_712
```

To make the signature work with ERC1271 with the guardian as a contract the only thing you need to do is to let `verifySignature` signature know it's a WALLET signature type first so `isValidSignature` is called on the guardian contract. So the signature sent onchain would look like this:
```
signatureData | SignatureType.EIP_712 | SignatureType.WALLET
```
So you just add an extra `SignatureType.WALLET` byte at the end of the signature data and that's it. This way `isValidSignature` is called first on the guardian contract (with as signature data the same data but the last `SignatureType.WALLET` byte stripped off) and then the signature data is validated against the guardian owner in `ERC1271Module` (the last byte is now `SignatureType.EIP_712` so it's a signature like normal).

Because of the recursive nature you can see it's very flexible while still being very easy. The wallet owner of the guardian contract could also be a contract and things would still work.

**Comment by adamchen0510** [comment]
Yes, I need use the correct signature type, thanks!
