### ISSUE TITLE
[Hebao]WalletConnect Support

### ISSUE THREAD

**Issue by adamchen0510** [Loopring/protocols#1087]
In order to support WalletConnect, we need to transact to any dapp from WalletConnect.
But there has onlyModule maybe for security issue.
![image](https://user-images.githubusercontent.com/13066091/79228977-e1656680-7e94-11ea-87b2-f0276185b5b0.png)
So we need and a transparent module to support WalletConnect.
There is a similar module named GenericDAppModule, 
![image](https://user-images.githubusercontent.com/13066091/79229255-4a4cde80-7e95-11ea-91a4-5fabf8b80a03.png)
but only support one dapp in one instance, if remove the dapp info it can support the WalletConnect.

**Comment by Brechtpd** [comment]
There is a `callContract` in `QuotaTransfers` and `ApprovedTransfers` that can be used to call any contract (with some limitations on either value transferred or number of signatures required).

Though WalletConnect is just a way to sign some transaction data, so we don't HAVE to support all calls that are possible. A good fit for WalletConnect seems to be the  `callContract` in `QuotaTransfers` that limits the value that can be transferred each day.

The idea behind `GenericDAppModule` is to allow ALL interactions with a certain dapp without any limits and just with a signature of the wallet owner, so the dapp needs to be safe for this kind of thing. So it kind of has a different purpose than the `callContract` functions and is not a good fit for a general WalletConnect integration.

**Comment by adamchen0510** [comment]
I see, I'll use the callContract to have a try, thanks.

By the way, what's the purpose of LoopringModule, it could be implemented by the callContract too. 
Now it don't limit the eth deposit by depositToDEX, but limit the ERC20 token as need approveToken in QuotaTransfers.

**Comment by Brechtpd** [comment]
In general there aren't really any benefits to dapp specific modules. If I remember correctly that was only done to make the app development easier because the necessary function calls the app needs to call could be easier. Everything should be possible using the general contracts. The dapp address can even be whitelisted so no quotas are applied and only the wallet owner needs to sign.

But `LoopringModule` does seems to have strange limitations. I would assume ERC20 approvals for the exchange shouldn't need `QuotaTransfers` so there isn't any limit. Also does  `LoopringModule` even support depositing ETH? I can only see it send `fee` as `msg.value`. The `msg.value` sent by the relayer is actually limited because the wallet owner needs to pay for it in meta transaction fees which uses the daily quota.

**Comment by adamchen0510** [comment]
![image](https://user-images.githubusercontent.com/13066091/79298922-23ce8800-7f15-11ea-9402-f6c7dd8804d0.png)
There was a patch fix deposit issue which add amount and deposit to exchange.

If the LoopringModule can be treated as whitelist by default, it need add approveToken which don't use QuotaTransfers and will have no limitations.
------
The msg.value sent by the relayer is actually limited because the wallet owner needs to pay for it in meta transaction fees which uses the daily quota.
------
This just mean the reimburse fee would exceed the daily quota? Although it may not in actual as daily quota would be dozens of ETH, but theoretically possible, so it's really strange limitations.
maybe we still need add exchange as whitelist by default for user experience.

and reimburseGasFee don't judge whitelist, if transfer to a whitelist address many times, it still possible to exceed QUOTA_EXCEEDED? I noticed Argent said itself paid for the transfer fee, we'll follow this?

**Comment by Brechtpd** [comment]
Ah I missed that patch, was looking at local outdated code. Seems fine now. :)

> If the LoopringModule can be treated as whitelist by default, it need add approveToken which don't use QuotaTransfers and will have no limitations.

It's the exchange contract that needs to be whitelisted, not `LoopringModule`. Well, you could do it like that as well but that will need 2 transfers which would be a bit strange. I think it makes much more sense to just approve the transfer in `LoopringModule` before the deposit so there are no limits on this.

> This just mean the reimburse fee would exceed the daily quota? Although it may not in actual as daily quota would be dozens of ETH, but theoretically possible, so it's really strange limitations.
maybe we still need add exchange as whitelist by default for user experience.

It's only for the msg.value sent by the relayer itself (e.g. to pay the fee if the user doesn't have ETH. In theory a user could also 'buy' ETH this way but that doesn't make a lot of sense). If the user has enough ETH in his wallet than there is no problem. Sorry for the confusion.

> and reimburseGasFee don't judge whitelist, if transfer to a whitelist address many times, it still possible to exceed QUOTA_EXCEEDED? I noticed Argent said itself pay for the transfer fee, we'll follow this?

It doesn't use the whitelist because it's a payment to the relayer not the (whitelisted) dapp. The `msg.value` sent by the relayer shouldn't be used for e.g. depositing ETH to the exchange, only for fee payments. So I think this will be fine. The fees paid by the user for his transactions shouldn't come close to his daily limit. And if it does, that's what the daily limit is for so actually works as expected. Otherwise an attacker could transfer all wallet funds to himself as a "fee payment" when doing a transaction on a whitelisted dapp.

**Comment by adamchen0510** [comment]
By using LoopringModule, we don't need add exchange contract to whitelist, the LoopringModule is just like a whitelist, deposit has no limit(eth now, if will add approve token in LoopringModule, erc20 tokens will has no limit too)
Kongliang will add approve token in LoopringModule.

> It's the exchange contract that needs to be whitelisted, not `LoopringModule`. Well, you could do it like that as well but that will need 2 transfers which would be a bit strange. I think it makes much more sense to just approve the transfer in `LoopringModule` before the deposit so there are no limits on this.

**Comment by Brechtpd** [comment]
Ah okay, seems like I misunderstood what you meant with the whitelisting. Looks like we're on the same page. :)
