### ISSUE TITLE
[Hebao]LoopringModule internal error in createOrUpdateDEXAccount

### ISSUE THREAD

**Issue by adamchen0510** [Loopring/protocols#1091]
Although create account success, we need clear these errors.

https://goerli.etherscan.io/tx/0x9e9b45755904b95d10538d76ffa5b5428a3e29539806b70542fb8e4d7bcb8b35#internal

![image](https://user-images.githubusercontent.com/13066091/79425978-14bf0700-7ff5-11ea-8488-389e338fb1dd.png)

**Comment by kongliangzhong** [comment]
This issue is caused by the following code:
    function getDEXAccount(
        address     wallet,
        IExchangeV3 exchange
        )
        public
        view
        returns (
            uint24 accountId,
            uint   pubKeyX,
            uint   pubKeyY
        )
    {
        bytes memory callData = abi.encodeWithSelector(
            exchange.getAccount.selector,
            wallet
        );
        (bool success, bytes memory result) = address(exchange).staticcall(callData);
        if (success && result.length == 96) {
            assembly {
                accountId := mload(add(result, 32))
                pubKeyX := mload(add(result, 64))
                pubKeyY := mload(add(result, 96))
            }
        }
    }

when creating a dex account, and the account does not exist yet, then the static call  `exchange.getAccount` will fail.

Because in the ExchangeV3.sol, we have the following code:
    function getAccountID(
        ExchangeData.State storage S,
        address owner
        )
        public
        view
        returns (uint24 accountID)
    {
        accountID = S.ownerToAccountId[owner];
        require(accountID != 0, "ADDRESS_HAS_NO_ACCOUNT");

        accountID = accountID - 1;
    }

when the account does not exist, then the `require(accountID != 0, "ADDRESS_HAS_NO_ACCOUNT");` will fail.

It does no harm to the whole account creating process but shows some error in the transaction trace. In order to fix this issue, we will have to update the getAccountID method in ExchangeV3.sol(ExchangeAccounts.sol, more precisely). 
So maybe this issue will not be fixed shortly.

**Comment by kongliangzhong** [comment]
@Brechtpd , please also take a look, and maybe we can get rid of the `require` line in getAccountID function in the new version of our dex smart contract code.

**Comment by Brechtpd** [comment]
I could change this in v3.5, but is this really necessary? It seems like throwing is a valid way in solidity to let the caller know that no account exists for `getAccount`. Perhaps a `hasAccount` could be useful.

In any case try/catch was recently added for these cases so these sub-function calls that fail aren't going away. Is there any reason we don't want any failing traces in the calls? This is perfectly valid to have so I don't see any reason to make sure we don't have any.

Another solution would be to have separate function calls in the module for creating accounts and updating accounts. This way we don't have to find out in the smart contract if the account exists or not. The app will know if an account is being created or not anyway.

**Comment by kongliangzhong** [comment]
I am okay with the failing traces in the calls.
