### ISSUE TITLE
[Hebao]why need confirmGuardianAddition and confirmGuardianRemoval

### ISSUE THREAD

**Issue by adamchen0510** [Loopring/protocols#1099]
Just like addToWhitelist, the guardian will be effective after pendingPeriod, don't need confirmGuardianAddition.
And confirmGuardianRemoval is the same.

**Comment by Brechtpd** [comment]
If I remember correctly it's mostly because of efficiency and simplicity. Because we have to run over all guardians sometimes and the list would contain guardians in different states. So even to just know how many guardians a wallet has you'd have to run over all guardians and check if the guardian is actually valid at the time or not. For example, we currently do this:

```
uint count = controller.securityStore().numGuardians(wallet);
require(count < MAX_GUARDIANS, "TOO_MANY_GUARDIANS");
```

This will have to check how many guardians are now active or could be active at some point of time in the future. (Hmm actually the current code isn't safe either, but can easily fixed. Will create a PR).

For whitelisted addresses we don't have that problem because we only need to check if a single address is whitelisted or not, we don't care about how many whitelisted addresses there are etc...

But sure, if you think it's worth it to not need any confirmations at the cost of some extra complexity than I'm okay with that.

**Comment by adamchen0510** [comment]
I see, by add confirmGuardianAddition, it would be efficient and simple for contract.

If just for count numGuardians, we can count guardians group num and pendingGuardian group num(which can be treat as guardian too) when addGuardian.
I know numGuardians is just an example, if we decide to remove confirm step, we need go through the codes.

For confirmGuardianAddition, it decided by our design, whether guardian can reject the addGuardian request, if can, it still need confirmGuardianAddition(else need every one can call cancelGuardianAddition to cancel the guardian addition).
But the first guardian don't need guardian confirm, so if need guardian accept this is a problem.

For confirmGuardianRemoval, it absolutely don't need guardian confirm.

By these two confirmation, relayer need create task for each wallet to confirm for the wallet. we need balance the effort.
It's just a discussion, and it's not a small task if decide to remove these two api and need more consideration.

**Comment by kongliangzhong** [comment]
resolved.
