### ISSUE TITLE
[Hebao]Majority signatures discussion 

### ISSUE THREAD

**Issue by adamchen0510** [Loopring/protocols#1138]
Now, if user want to recover his wallet, he need pick the majority guardians(signers in function recover) to sign the data in recover:
![image](https://user-images.githubusercontent.com/13066091/81251477-f6798380-9055-11ea-8e94-1342c6ec545d.png)
Every one of the signers need sign the data to match the signers.length in verifySignatures:
![image](https://user-images.githubusercontent.com/13066091/81251738-91725d80-9056-11ea-9814-ad578d67d8a4.png)

The problem is:
The owner need pick the guardians which much sign the data for him, else it can not recover the wallet.

The suppose case is:
The owner can pick all the guardians(or empty treat as all guardians) as signers and can success when random n/2 +1 of the guardians sign the data.

**Comment by kongliangzhong** [comment]
The point is that the owner has to choose all the singers and the number of signers must be greater than half of the total number.  And all the chosen singers' signatures are required. 
I'm not sure this is what we expect.
@dong77

**Comment by dong77** [comment]
@Brechtpd I think it's not a bug, but an issue what will make recovery hard in realitity.


in https://github.com/Loopring/protocols/blob/a10b76049a518212995450d560172cfdcf1a4a8a/packages/hebao_v1/contracts/base/MetaTxModule.sol#L167, the `data` fields contain the list of guardians who actually signed the meta tx, but it is also the data that each guardian need to sign. The problem is that before enough guardian actually signed the tx, we don't know the actual list beforehand.

There are two way to fix it:

1.  make signers in `address[] memory signers = getSigners(wallet, data);` represent the list of guardians who we requeste to sign the recovery (not the actual signer), but we need to change `verifySignatures` so that we verify a majority of the signers provide signatures, not all of them.
1.  Change `address[] memory signers = getSigners(wallet, data);` to something like this: `(address[] memory signers, bytes   memory otherData) = getSigners(wallet, data);`, and ask each signer to sign against `otherData`, not `data` itself.

I'll be happy to jump into a call once you are available.

**Comment by Brechtpd** [comment]
Other functionality that needs to have a majority are as hard as recovery, so it's not specifically difficult just for recovery (though of course recovery is the most important one).

I think the only good way to fix this is to remove `address[] signers` from the function call and somehow check the signers elsewhere in the meta transaction. This way it is fixed for all functionality without any special cases and potential unique issues (like replay protection).

**Comment by Brechtpd** [comment]
See #1142 for possible solutions.
