### ISSUE TITLE
[Hebao] Add approveThenDepositToDex in LoopringModule

### ISSUE THREAD

**Issue by adamchen0510** [Loopring/protocols#1152]
Just like approveThenCallContract in QuotaTransfers and approveThenCallContract in ApprovedTransfers, add approveThenDepositToDex api.

**Comment by Brechtpd** [comment]
Maybe just approve each time for every deposit?

`executeTransactions` could also be used to first call `approveExchange` and then `depositToDEX` in a single meta tx.

**Comment by adamchen0510** [comment]
> Maybe just approve each time for every deposit?
It's decided by user, we can show a very large approve value, but user can modify the approve value to a little one equal to deposit value, so need approve again when deposit again.

> executeTransactions could also be used to first call approveExchange and then depositToDEX in a single meta tx.
This has quota limitation, right? Our Loopring module just like a trust list dont limit the deposit value.

so I think it's better to add the approveThenDepositToDex

**Comment by Brechtpd** [comment]
> > Maybe just approve each time for every deposit?
>
> It's decided by user, we can show a very large approve value, but user can modify the approve value to a little one equal to deposit value, so need approve again when deposit again.

 If the approval happens automatically and approves exactly what is deposited directly inside `depositToDEX` I don't see why users would need to care about how much is approved. If they deposit again it will be approved again automatically. Seems to work fine, no? I understand why a large value is set when not using a smart wallet because it's bothersome to approve each time, but in this case the user won't even notice and it works exactly as expected.

> > executeTransactions could also be used to first call approveExchange and then depositToDEX in a single meta tx.
> 
> This has quota limitation, right? Our Loopring module just like a trust list dont limit the deposit value.

`executeTransactions` doesn't add any extra limitations. It just allows calling multiple functions on the module, nothing more.

> so I think it's better to add the approveThenDepositToDex

Fine for me, but I don't think it's that useful because we know exactly what the user tries to do so we can do it for him. For `approveThenCallContract` we have no idea what the call does onchain so it makes sense to specify what the approved amount needs to be.

**Comment by adamchen0510** [comment]
OK, I can use executeTransactions if need.
