### ISSUE TITLE
[loopring4] allow permission-less account registration 

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1168]
If Alice would like to send some tokens to Bob on layer-2, if Bob does not have an Loopring account, Alice should be able to create Bob’s account by paying the fees. Bob’s initial EdDSA pubkey must be 0 for security considerations. Alice then cAn do the offchain transfers. 

Bob will have to reset the account key for the first time before he can get the control.

**Comment by Brechtpd** [comment]
This is a good idea.

In 3.5 this is kind of already possible by using an Agent that would allow this. But in 3.5 only the account owner can authorize agents. So Bob would now have to authorize the Agent himself before the account can be created by that Agent, which doesn't make sense in this case. I thought about allowing exchanges to whitelist agents for all users, and I think this shows that this is indeed useful. 

Building this into the exchange contract is of course also possible, but I think it's also a good fit for Agents because this is the reason it was created (do things for a some user). The changes necessary for this are:
- Allow the Exchange owner or the Loopring protocol (owner) to whitelist agents
- Implement this behaviour in an Agent

**Comment by Brechtpd** [comment]
On the other hand, this is so easy we may as well do this directly in the exchange contract.

**Comment by dong77** [comment]
I would vote for the native support.

**Comment by dong77** [comment]
https://github.com/Loopring/protocols/pull/1228
