### ISSUE TITLE
[Protocol 4.0] Balance the Merkle tree

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1218]
> I think I proposed something similar before.

The account id is incremental by 1, this end up with a off-balance Merkel tree. The left tree is always *heavier* than that right one, as seen in the diagram below (in the tree on the left).

![WechatIMG2](https://user-images.githubusercontent.com/1710087/83002350-8b611280-a03f-11ea-926b-ec49a40aa4aa.jpeg)

As we increase the height of the tree, we hope the update to the Merkel tree can be parallelized using multiple machines. This off-balance property of the current Merkel tree makes some shards has no update to do and a few shards have all the work.

Can we place account nodes differently so the tree is more balanced, like the tree on the right?

**Comment by dong77** [comment]
The proposed balancing approach can also be seen as a new way to generate the next account ID. Current we use `accountId += 1`, but we may now use two variables, one is the `accountIndex` to track the index, then the accounted (location the Merkle tree as:

```
accountIndex += 1;
accountId = bitReverse(accountIndex)
```

where bitReverse is a function to reverse every bit in the integer, for example:

1000 -> 0001,
1100 -> 0011,
1010 -> 0101

**Comment by Brechtpd** [comment]
It is possible, but I just wonder what the problem is that this solves. It seems like this optimization depends on either the Merkle tree being largely empty or on a bit of luck that the updates that need to happen are spread out. What is the bottleneck? The hash calculations? IO?

Batch updates in a SMT are already very parallelizable for any leafs that need updating by calculating the new hashes per level (see https://youtu.be/cF6sG47pcws?t=1641). Doing the updates like this is very parallelizable, in all cases. There are only `O(tree_height)` sequential steps, but all the hash calculations in each step can be fully parallelized. So in theory, if each hash calculation is done on a different CPU, doing all the Merkle tree updates only takes `time_to_compute_single_hash * tree_height`, which seems to be the minimum that can be achieved.

But maybe the bottleneck is IO? I think the data can be stored however makes sense, so maybe leafs aren't stored in the order of their addresses if that helps?

**Comment by dong77** [comment]
Current performance bottleneck is the update to the Merkel tree (we are maintaining an in-memory Merkel tree in one server). To enable more than 200 trades per second. We need to partition the Merkel tree into multiple shards and perform updates to sub-trees in parallel in multiple servers, then consolidate sub tree roots into the final tree root by a single server. 

The current issue is that shards with smaller account ids are filled earlier so the updates to account sub trees end up in a few hot shards.

**Comment by Brechtpd** [comment]
Okay, I think I understand how this could make this could make things a bit easier depending on how things are setup. But I don't think it's necessary to achieve better performance.

I think the work that needs to be done as fast as possible is:
1. Updating the account leafs so that the new account leaf hash can be calculated: easily fully parallelizable on the account level.
2. Updating the Account Merkle tree: very parallelize (O(merkleHeight), the minimum achievable). 

Both are very easy to do very efficiently if they are done on the same machine that has access to a lot of CPU cores. But the amount of cores is still a bottleneck. If 2000 accounts need to be updated and we only have 50 cores available, this will still take `2000/50=40` serialized account updates.

Okay, so multiple machines are used to ideally have 1 CPU core/account update (you could probably parallelize inside the account update as well, but let's say we don't do that).

Two options are available:
- The accounts are stored distributed over multiple machines. Using `bitReverse(accountIndex)` to distribute the accounts will likely work okay, but that's not necessarily the best way to do it. You could probably find even better methods to distribute the work, like making sure very frequently used accounts are stored on different machines. No account data needs to be moved around for this method everytime, but where the account is stored has some impact on how efficient the updates can be done (but accounts can be moved between servers at will to mitigate this if the distribution is not efficient).
- All accounts are still stored on a single server, but the account data is sent to the different machines and processed there, the resulting hash (and maybe updated state) is sent back. This of course assumes that all accounts can be stored in memory on a single machine. Because data is moved around, this may not be very efficient (depends on how fast this can be done).

So at this point we have all the account hashes and the only thing we now need to do is batch update the main Merkle tree. This Merkle tree structure could be stored in different parts on different machines, but I think it's very unlikely that will be necessary. If the accounts are stored elsewhere, than we just needs to store a bunch of hashes. So at the lowest level we have at most `((2**24) * 32) / (1024*1024) = 512MB` of hashes, so storing the complete Merkle tree in memory will use less than 1GB of memory. And we just need to calculate a bunch of fairly easy to calculate hashes, so I can't really see this taking up really any significant amount of time, even with a moderate amount of cores (Poseidon hashes may be a bit slower than other common hash functions, but they are not that slow).

This is just my idea of how it could work, and I could very well be wrong, so please correct me if I'm seeing this to optimistically. :) 

So I think using `bitReverse(accountIndex)` may make sense to make it easy to understand (complete sub-trees stored on different machines) but I think you can achieve the same without doing this on the protocol level. But it's super easy to do on the protocol level, so if that makes things easier for the relayer somehow than let's do this.

**Comment by dong77** [comment]
Ideally, the cross-network RPC invocation is minimized. When we have multiple shards and want to update account X, we should be able to calculate which shard account X resides only based on the value of X (the account ID) without a round trip to another server for shard lookup. 

Each shard will maintain its own shard root, which will be cached and updated only once if there are dirty leafs. The Tree root will be calculated dynamically by first querying all shard roots.

Note that shard roots are not necessarily account nodes.

**Comment by Brechtpd** [comment]
I understand, but I don't see why you can't just "shard" the account leafs with `bitReverse(accountIndex)` if that's what you want. I would expect the CPU bottleneck to be there, not in the Accounts Merkle tree update itself (though hard to say for certain without measuring, and this needs a good parallel implementation). 

Not saying it's not cleaner is some ways to shard at a higher level in the tree, but it would surprise me if that has a significant performance difference with just sharding at the account level. Just trying to find something that could work just as well for the current Merkle tree.

**Comment by dong77** [comment]
We want to literally shard on the account level. But we don't want to shard accounts randomly, because if we do that, we have to have a DB to persist which shards contain which accounts. The issue with this approach is that to update each account, we'll need to do a shard-lookup. If we can avoid this lookup per account update, we may increase throughput by 2X or 1.5X. 

Automatically assign shards based on account ID is also less error-prone and flexible. For example, we can initially have only 8 shards, then if we want to increase to 16 shards, we just need to change this parameter, and restart the system, then we have 16 shards. We don't have to change the account-to-shard DB to split each shard into two.

**Comment by Brechtpd** [comment]
Number of shards: 8
AccountID: 12
Account stored on server `AccountID % numShards = 4`
Account leaf hash updated at address: `AccountID = 12` in Accounts Merkle tree

I don't see why a lookup is necessary in this approach. The only difference I see is just that the Accounts Merkle tree itself (so just the hashes in the tree) is not sharded, which I assume makes no big difference, but I could be wrong.

Let's talk about this tomorrow, I think we're just talking past each other. :)

**Comment by dong77** [comment]
Brecht, if we have 8 or 16 shards, which is quite possible to be the case in production, then the Root Service that computes the tree root only needs those 8 or 16 hashes as input. It doesn't maintain the top part of the Merkle tree at all. In other words, shard roots are not accounted nodes. Why do we design sharding this way?  The answer is to minimize the data to be transferred from Shard Services to the Root Service. 

This also means each shard will have to have all the information regarding the sub-tree it managed. Two account nodes that belong to the same sub-tree cannot be partitioned to more than one shard. Otherwise, it will need cross-shard communication.

We want each shard not aware of any other shards.

**Comment by Brechtpd** [comment]
> Brecht, if we have 8 or 16 shards, which is quite possible to be the case in production, then the Root Service that computes the tree root only needs those 8 or 16 hashes as input. It doesn't maintain the top part of the Merkle tree at all. In other words, shard roots are not account nodes. Why do we design sharding this way? The answer is to minimize the data to be transferred from Shard Services to the Root Service.

Sure, but in our case the amount of data is minimal (for a block of 1024 trades it's just 2048 hashes at most, which is just 64KB total in the worst case shard over all shards). But okay, fair enough.

> This also means each shard will have to have all the information regarding the sub-tree it managed. Two account nodes that belong to the same sub-tree cannot be partitioned to more than one shard. Otherwise, it will need cross-shard communication.

> We want each shard not aware of any other shards.

If there are just < 1024 accounts, and we have 4 shards, we could also just shard [0, 256[, [256, 512[, [512, 768[, [768, 1024[ (so just sharding the Merkle tree of height 10 at the bottom left into 4 shards). The siblings at the the top of the Merkle tree are static in this case anyway, we don't have to necessarily have to start the sharding at the top of the Merkle tree if only a small part of the left part is used. Or we can shard in small sub trees of accounts (let's say of fixed height 10) and these are distributed over multiple servers in a deterministic way. Very flexible, and this will even minimize the already small amount of hashes that need to be shared otherwise if we do it per account.

If we're CPU limited because of the Poseidon hashing, I think there's also a lot of room for optimizations in our Java code for this. 

But okay, I will stop bothering you with this haha. ;)
