### ISSUE TITLE
[Loopring 4.0] Add protocol fees to transfers?

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1229]
Why not?

**Comment by Brechtpd** [comment]
- Users are not used to pay a certain fee percentage on the amount transferred. This also doesn't make much sense.
- We would have to raise the protocol fee on the fee amount specified for the transfer. But an operator can easily work around that by not charging any fee, but just do 2 transfers with no fee. The actual transfer at some nonce, and the transfer that pays a fee to the operator at nonce + 1. It only makes sense to do this if the protocol fee is very high (the operator has to pay for 2 txs instead of 1), but it will need to be high because it is charged directly on the fee amount. So to make it comparable to trades it would need to be 60% of the total fee.

So it doesn't make a whole lot of sense to handle this in the circuit because it doesn't really add anything. The operator can still work around it. Also the fee will be largely the same for all transfers (also differently from trades where fees that are paid will vary wildly).

If we really want to charge a protocol fee for transfers I think it would make much more sense to just check the block for the number of transfers in it and just charge the operator `transferProtocolFeeETH * numTransfersInBlock` onchain. Easy and efficient, and no way around it.

**Comment by dong77** [comment]
Lets put this aside for now.
