### ISSUE TITLE
[Loopring 3.6] Allow operator to specify the max gasLimit for ERC20 transfers

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1231]
With such flexibility, the operator can set the onchain withdrawal fee high enough to cover the most expensive transfers, then advocate users to do off-chain withdrawals. For each token, the operator can determine the minimum offchain withdrawal amount and the fee percentage.

**Comment by dong77** [comment]
@Brechtpd What if we add per-token withdrawal fee (in ETH) and gas limit settings, if missing, then fall back to the default?

**Comment by Brechtpd** [comment]
Yes, that makes a lot of sense, especially the gas limit.

I'm not sure how useful the per-token onchain withdrawal fee setting will be, because I don't think it will really be used much at all once offchain withdrawals requests are active, which provide all the flexibility we want. But I guess it can't hurt to just get the withdrawal fee from e.g. the deposit contract (which could implement some additional logic per token/account owner) and the protocol just enforces that the fee the user pays is `min(withdrawalFee, maxWithdrawalFeeImposedByProtocol)`.

**Comment by dong77** [comment]
this is a duplicate of https://github.com/Loopring/protocols/issues/1241
