### ISSUE TITLE
[Loopring 3.6] Do not request operator to sign settlement blocks or relax nonce

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1239]
It seems that the operator needs to provide a signature against the data in each settlement block. This doesn't seem to be necessary.

**Comment by Brechtpd** [comment]
The operator needs to sign the settlement data because the operator pays the protocol fees. These funds are transferred out of his account, so a signature is required to authorize this. Otherwise the operator could use any user's account to pay the protocol fees.

It's possible to check the owner of the operator account ID onchain and check that the owner == msg.sender of the block submission, but this seems to be quite limiting as well that the onchain operator also needs to be the owner of the operator account.

Not sure if there's a better solution to this.

**Comment by dong77** [comment]
According to @lydy, the operator's nonce will add by 1 when signing this settlement block. Is it possible not to require the nonce +1? What's the security implication?

The reason is to maintain as little information regarding the operator's state as possible to make the system more fault tolerant.

**Comment by dong77** [comment]
Based on our discussion in the other issue, I think it's ok to increase the operator's nonce by 1 and ask him to sign, so a block full of dummy request will still modify the Merkel tree root. But besides the nonce, the other part of the tree should be the same.

**Comment by dong77** [comment]
Brecht, I'm closing this issue.
