### ISSUE TITLE
[Loopring 3.6] add withdrawal ID to the WithdrawalFailed event

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1243]
This will help the relayer to parse the data to build a DB for the frontend to enable the user to manually  transfer the withdrawal transfer again.

**Comment by dong77** [comment]
@lydy please make sure this is what you want.

**Comment by Brechtpd** [comment]
I think from 3.5 on this won't be needed because the user doesn't need this info any more. The function that need to be called is now `functionwithdrawFromApprovedWithdrawal(address owner, address token)`. The only thing that needs to be known is the owner and token address for the failed withdrawal, that's all (and this data is available in `WithdrawalFailed`). If there are multiple failed withdrawals for a certain token for a user only a single call to `functionwithdrawFromApprovedWithdrawal` is needed.

**Comment by dong77** [comment]
Great. issue closed.
