### ISSUE TITLE
[Loopring3.6] support unlimited number of tokens. 

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1259]
With a few bull market, there are likely to be thousands more tokens. And we may delist some old tokens and list new tokens. 

The current 1024 token support will be a real limitation to us. Therefore, I propose to support reusable token slots. On layer1, let’s keep the total deposit balance for each token. Once this balance is 0, and this token is disabled, we can register a new token with the same slot. 

This feature depend on another feature: the operator should be able to offchain withdraw tokens for users with their signatures.

**Comment by Brechtpd** [comment]
> The current 1024 token support will be a real limitation to us. Therefore, I propose to support reusable token slots. On layer1, let’s keep the total deposit balance for each token. Once this balance is 0, and this token is disabled, we can register a new token with the same slot.

Very difficult to get the balances of all users back to completely 0 which is why we want to remove shutdown mode (rounding errors, too many accounts etc...). But I guess it could work if the token wasn't too popular so not too many people have the token and the operator can do withdrawals for tokens that are disabled (and we don't support things like perpetuals which can store tokens in multiple margin positions which are even harder to get out).

But if we think 1024 tokens is a limitation, why not just increase the limit to 4096 or even 65536? There's some extra proving cost which is pretty small, or even insignificant with high gas prices, compared to the onchain cost, see https://github.com/Loopring/protocols/issues/1034#issuecomment-617812146 for some stats about this: compared to 3.5 an increase of just 6% to have a max of 4096; 18% increase to have a max of 65536. Otherwise we would have to depend on delisting tokens. Delisting tokens for trading makes some sense, but for transfers it would be a bit strange, especially if the rollup is used as the wallet for the user.

I'd rather just have a bigger limit which will always be useful rather than having to implement special logic to make this possible in some special cases.

> This feature depend on another feature: the operator should be able to offchain withdraw tokens for users with their signatures.

These are offchain withdrawal requests right? If they need the signature of a user. Or do you mean without their signature? So if the token is disabled the operator can withdraw their tokens

**Comment by dong77** [comment]
4096 seems good enough.

**Comment by Brechtpd** [comment]
Agree, but I don't think we'll be using Merkle trees in 2 years. :)

**Comment by dong77** [comment]
That’ll a fair point. :)

**Comment by dong77** [comment]
Brecht, I think 4096 is good enough, I don't even have to make them resellable.But I have this idea, just want to make sure we don't miss it:

Is it possible that we use a similar idea of trade history so we can support unlimited tokens but with only 4096 slots? If the balance of a slot is 0, it can be reused by a deposit of any token.

**Comment by Brechtpd** [comment]
Hmmm yes, I think it would be possible by storing the tokenID inside the leaf. I'm not fully sure of everything this would change. It's hard to enforce that only a single address is used for a certain token so balances could be spread over multiple slots by an operator if he wants to do that, though I don't immediately see a real problem with that except users won't like it. I guess this could be solved by only letting a user assign which slot would be used for a token, but that doesn't seem very realistic as users would have to first create a leaf before the operator can use it for receiving tokens, which wouldn't be very user friendly for transfers or even trades.

It's an interesting way to do it which I hadn't really thought about yet. The original rollup design from Barry only had a single Accounts Merkle tree without a sub tree for tokens because each account only could store the balance of a single token. The drawback here is that every leaf is its own full account, so the public key and nonces aren't shared and really need to be created separately by the user. So your idea would be a hybrid between them.

So I would say it's a good idea currently! It doesn't allow for unlimited tokens because we still need to have a max number of bits for the tokenID in the data availability, but this would lower the cost to update the Merkle tree inside the circuit by only needing a smaller Merkle tree. This tree still needs to be large enough (256 or even 1024) so savings wouldn't be very big, but still significant (maybe ~5-10% less constraints).

**Comment by dong77** [comment]
I think the question we should have asked ourselves is how long we believe this version (3.6) should be maintained in production before we migrate to use better technologies alternative to Merkel tree. I would say 2 years minimum and 4 years maximum.

**Comment by Brechtpd** [comment]
I'm very optimistic about all the progress being made (ZKPs/Ethereum/accumulators/...) so I would say 1 - 2 years. 4096 seems to be more than enough to me as well.
