### ISSUE TITLE
[Looopring 3.*] Support unlimited amount of accounts

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1260]
The current limitation of 3.5 and 3.6 is that we have a fixed account tree so the maximum of accounts we can support always have an upper bound. For clarification, let's call the tree for each account the Account Tree, and the top part of the tree with all Account Tree Roots as leaves the User Tree.

The idea is to make User Tree dynamic height instead of being fix. It's pretty simple:

- Initially, the user tree's height is 1, so the capacity (number of possible accounts) is 2.
- When this tree is completely filled, we make it the left sub-tree of its parent and use another tree as its right sibling, this tree's height is always 1.
- We repeat this process when new users register.

The registration of the first 10 accounts are shown below:

![WechatIMG67](https://user-images.githubusercontent.com/1710087/83964945-bc183600-a8e2-11ea-891b-450b66d0386e.jpeg)

The rules are quite simple for implementation.

## Pros

- The user tree can grow to support unlimited accounts
- The average number of hashes to compute for the same set of account nodes will be smaller than a fixed tree. Especially in the early stage of user acquisition, the tree will be much smaller than the current settings.

## Cons

- Certainly more complicated (but manageable)
- Sharding based on account Ids as in 3.5 will be impossible.
- **The circuit may not be able to handle the dynamic nature of the tree.**

**Comment by Brechtpd** [comment]
The circuit can support this, but this would need additional trusted setups and potentially even smart contract updates.

- The circuits need to be updated because they need to check lerger trees. So we need a new trusted setup every time the tree changes.
- The data-availability data needs to have enough bits available to store the accountsIDs/tokenIDs. So if they need more bits than available at a points we need to update smart contracts and circuits.

Increasing the tree size by 16x the capacity is fairly cheap at this point. The added cost from 3.1 with 1M accounts to 16M accounts was just 6% in number of constraints, and 4 bits/account extra DA data (so just a single extra byte for trades and transfers).

Let's say we want to do another increase the capacity again x16. This would mean we'd just have the same extra cost as going from 1M -> 16M accounts, so again just an additional 6% increase in constraints and an additional 1 byte of DA data for trades/transfers, and we have 256M accounts.

The logarithmic nature of a tree makes the difference between small trees and very large trees quite small in terms of costs.

So I would just keep things easy here as well and just make the tree large enough. If we had no trusted setup and no on-chain DA this would be nice way to save on some costs while the tree can remain smaller, but I don't think it's worth it at this point.

> The average number of hashes to compute for the same set of account nodes will be smaller than a fixed tree. Especially in the early stage of user acquisition, the tree will be much smaller than the current settings.

The relayer can do already this for the calculations it needs to do. But even at our current tiny 2,200 users we're already using 12 levels (out of 20) in the Merkle tree. :)

**Comment by dong77** [comment]
I don’t think we should proceed in this direction anytime soon. Just want to stay open minded for future updates.
