### ISSUE TITLE
[Loopring 3.6] support for efficient batch account registration 

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1274]
Suppose an existing wallet will partner with us and they are willing to enable L2 transfers by batch registering accounts for all their users. Maybe we can support them with a batch registration feature so they don’t have to file too many onchain requests.

**Comment by Brechtpd** [comment]
Yes, that's a great idea. It's even possible to allow registering accounts for users without it having to be processed by the operator if the EdDSA key remains 0, it's just mapping the account ID to the Ethereum address onchain and that's it. This will be cheap (around 25,000 gas or so/account registration or so). There could also still be a small additional cost to guard against a Sybil attack, but if our accounts tree is big enough even that won't be a concern so it could just be the gas cost.

The only thing we need to change to allow that is to still allow registered users to have all zero keys. We currently forbid that onchain so we can check if the account is registered inside the circuit just by checking the public keys of the account. But that can easily be changed to just puting `numAccounts` into the circuit and checking that `accountID < numAccounts`. With the current bit reversed accountIDs this still works, we just need to reverse the bits again in the circuits before doing that check.

**Comment by Brechtpd** [comment]
The only really cheap way to add new users is to not touch anything at all. Otherwise the cost is at least 20,000 gas for each new user, which is quite a lot.

The way zkSync works, and I guess starkex as well to some level otherwise they wouldn't have been able to onboard 1,000,000 users in the demo pretty cheaply, is to store the Ethereum address inside the account leaf. This way we can allow transfers to Ethereum addresses that don't have an account yet, without having to touch any onchain state (so basically as cheap as a normal transfer at 300 gas or so).

So there are different stages an account can be in:
- Only exists in the Merkle tree, but no EdDSA keys yet. The user can't do anything completely inside the rollup yet.
- The user can set his EdDSA keys cheaply by giving the operator an ECDSA signature (cost < 5,000 gas). At this point the user can do everything inside the rollup.
- Perhaps it's still needed in some use cases to actually know the mapping between accountID <-> Ethereum address onchain. In that case we have an operation that actually does that link onchain (costly > 20,000 gas).

Even without EdDSA keys we could allow certain operations like transfers by checking the user's ECDSA signature for the operation onchain instead.

**Comment by dong77** [comment]
I'm thinking whether dropping the account ID concept entirely is an option? Then authentication can be done using ECDSA onchain or EdDSA offchain if the key is non-zero.

**Comment by Brechtpd** [comment]
The account ID is still important for efficiency. For normal transfers/trades we only want to put the account ID onchain because it uses a lot less data than always the full Ethereum address, that would reduce the scalability by ~3x. So in normal scenario's we still want to use accountIDs, just for certain transfers we use the more expensive transfer to an Ethereum address.

The account ID is also the address of the account in the Merkle tree, so in any case it will end up being used. Like if we transfer to an Ethereum address, we will still need to put the account ID onchain as well because otherwise we don't know which leaf was updated by the operator (as there could be multiple leaves with the same Ethereum address).

**Comment by dong77** [comment]
@brecht, since account registrations are implicit without any onchain requests, I think we can close this issue.

**Comment by Brechtpd** [comment]
Yep.
