### ISSUE TITLE
[Loopring 3.6]  Fine-grained permission control

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1296]
The general idea is to make the protocol more decentralized and not rely on the same owner/operator.

Currently, the owner addresses stake LRC to become the owner, then get access to certain functions such as shutdown, startMaintainMode, etc. But if we think from the core protocol's perspective, it's all about access control: who is allowed to call certain functions.

We can abstract the access control to different roles, the most extreme case is that for any function that can modify the smart contract state, we give it a designated address and only this address can call the function. The address is supposed to be a smart contract address that manages its own logic to authorize or deny calling the core contract. We can call these contracts the Operator Contracts.

So for the `shutdown` method, the core protocol will have an `address shutdownOperator`, and for 'registerToken` we will have an `address registerTokenOperator`. But they may have the same value, in such cases, a TokenAndShutdownOperatorContract can be created to manage access to both methods.

We'll need a special `address accessControlOperator` who manages the operators for different functions.

**Comment by dong77** [comment]
With such a design, we can remove the maintenance mode as suggested in https://github.com/Loopring/protocols/issues/1280, as long as a submitBlockOperator is designed right, some other operator can continue submitting blocks, and we can be the privileged operator to regain the access.

I expect the initial Operator Contracts can be very simple as it's trivial to upgrade.

**Comment by Brechtpd** [comment]
> So for the shutdown method, the core protocol will have an address shutdownOperator, and for 'registerTokenwe will have anaddress registerTokenOperator`. But they may have the same value, in such cases, a TokenAndShutdownOperatorContract can be created to manage access to both methods.

Do you want to implement this in the core protocol? Can't we do this using the operator/owner contract setup just by creating custom contracts for these?

Just to give an example, in maintenance mode, when other operators jump in to submit blocks, the custom operator contract could even check each tx in the block and make sure only blocks with withdrawals are submitted. If the main operator contract submits blocks none of these checks would be done. Of course, similar things can be done for the different functions that can be called on the exchange contract. But just to show that this custom logic can be very complex, and perhaps doesn't really depend much on what function can be called by an address, but more with what data.

You could argue that even the owner/operator distinction is unnecessary and everything can be handled in a single contract, though I think that distinction kind of makes sense because the operator keys need to be online so have worse security by default, so if no custom contracts are used it's still secure by just using different addresses for both.

**Comment by dong77** [comment]
Let's talk about this topic next week.

**Comment by dong77** [comment]
closing this issue to keep the core protocol as simple as possible.
