### ISSUE TITLE
[Loopring 3.*] Instant interest accruing on layer 2

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#1329]
One of the benefits of layer 2 + a deposit contract that stores funds in something that gains interest somehow is that user are still fully liquid on layer 2 regardless where the funds are stored. This is better than doing it on layer 1 as funds are stored elsewhere and users would need to deposit and withdraw to have access to their funds. Even for traders this is great because they earn interest even while having orders open.

The other benefit is that it's completely transparent for users. Users deposit or receive funds and immediately they start to earn interest, they don't even have to think about it or pay for any of the costs associated with it otherwise on layer 1. This is great for people don't have only small amounts in their accounts, the gas costs to put these small balances in a dapp would be greater than the interest earned in a year, so for these people bulk investing on the rollup level is the only feasible way to earn interest.

So I think this is a especially attractive use case for mainstream users. They deposit funds, start accruing interest in their accounts and can do transfers/trades without limitation. It couldn't be simpler. Super easy user experience that everybody is already familiar with.

One drawback with our current system is that interest accrues on layer 1 but is not immediately reflected on layer 2. Either users would have to withdraw to get their interest or some central party needs to distribute the interest to users at regular intervals on layer 2 (not trustless).

Distribution at some regular intervals is I think acceptable, but it would even be better if interest accrues immediately on layer 2 so all that isn't necessary. This is possible by using a similar mechanism as used for 4.0 for the funding rate and is actually quite simple to do. But it could be expensive if this is enabled for lots to tokens, so I think we only want to enable this for a select few tokens (like DAI, ETH, some stable coins etc...). This would also help for tokens like on Aave where interest is accrued directly on the token itself.

So in the end not really important in theory, but I think in practice if users would see their balance increase in real-time on layer 2 they would very much prefer that over a monthly distribution or something like that. They would immediately see this is something that's better than traditional banks for example in a very cool and easy to understand way.

**Comment by dong77** [comment]
I thought about this quite a lot after a discussion with engineers in Shanghai. I started to realize that maybe we are doing it wrong.


When we put money into a DeFi product, usually the DeFi protocol will mint some ownership token for us. For example, cDAI represents the ownership of DAi in Compound. The amount of cDAI to mint for newly deposited DAI is usually calculated as follows: 

```
function getAmountToMint(unit amountToDeposit) returns (unit amountToMint) {
    return amountMinted * amountToDeposit / (amountDeposited + getTotalEarning());
}
```
If we burn the newly minted cDAI to withdraw DAi, then:

```
function getAmountToWithdraw(unit amountToBurn) returns (unit amountToWithdraw) {
    return amountToBurn * (amountDeposited + getTotalEarning()) / amountMinted;
}
```

Lets see a concrete example: assume users deposited 100DAI collectively and get 1000 cDAI, and there is 50 DAI earnings already. Wen someone deposit 10 more DAI, the amount of cDAI is: `1000 *10/(100 + 50) = 66.67`. Now if he burn these 66.67cDAI immediately, the amount of DAI he can withdraw is `66.67 * (110 + 50)/(1066.67)=10`

We can notice that new user's participation doesn't change the amounts of cDAI of all previous participants. We can do it the power way, using an *index* so all the previous participants' balances will be increased, and in the meanwhile, keep the new user's cDAI balance as the same as the DAI he deposited. But the first approach is **much simpler**.

With the first approach, all users can claim DAI proportionally, this is also very straightforward.

-----------

When we enable a Deposit Contract to earn interest for Ether, the "ether" deposited into our exchange is no longer Ether, it's a ownership token to a specific fund containing Ether. Maybe we don't want to allow our Deposit Contract to earn interest at all (so no index is necessary), we can simply use layer-1 composition to list the ownership token.

----------

We can make the ownership minting, authorization, and exchange deposit an atomic operation; and make withdrawals and burning another atomic operation. So the ownership token never lives out of the exchange scope (no address other than the exchange can own those tokens). But the wrapping can live outside of the core protocol in fund management contract, instead of making the protocol complicated.

**Comment by Brechtpd** [comment]
Agreed, some minor differences but not worth it.

> We can make the ownership minting, authorization, and exchange deposit an atomic operation; and make withdrawals and burning another atomic operation. So the ownership token never lives out of the exchange scope (no address other than the exchange can own those tokens). But the wrapping can live outside of the core protocol in fund management contract, instead of making the protocol complicated.

Yeah you're probably right that doing it in a dedicated contract is better, even if it increases gas costs.
