### ISSUE TITLE
[Loopring 3.6] Withdrawal Contracts

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1372]
I had this idea yesterday when we talk about how to migrate users from 3.1 to 3.6.

It will be great if we can allow a user to authorize a withdrawal for a given token so the user's token balance will be withdrawn from 3.1 and automatically deposited into 3.6. I don't think this is currently possible, but I hope it will work when we decide to migrate users from 3.6 to another version.

We can allow users to withdraw to "withdrawal contracts". A withdrawal contract is one that implements this function:

```solidity
function onReceiveLoopringWithdrawal(
    address user,
    address token,
    unit amount,
    bytes calldata data,
    bytes calldata sig)
    returns (bool)
}
```

In our protocol, we check if the recipient address is a contract that supports the `onReceiveLoopringWithdrawal`  function (using ERC165), as follows:

```solidity

function withdrawToken(token, user, recipient, amount, data, sig) {
    token.transfer(recipient, amount);
    if (recipient != user && isWithdrawalContract(recipient)) {
        WithdrawalContract wc = WithdrawalContract(recipient);
        // will have to limit the gas usage here.
        bool result = wc.onReceiveLoopringWithdrawal(user, token, amount, data, sig);
        require(result, "must be true"); // we should allow failure by reverting the token transfer and re-transfer the token to `user`
    }
}

```

With such a design, we can implement a MigrationWithdrawalContract as follows:

```solidity

```solidity
function onReceiveLoopringWithdrawal(
    address user,
    address token,
    unit amount,
    bytes calldata data,
    bytes calldata sig);
} {
    require(msg.sender == currentProto), "UNAUTHORIZED");
    if (data.length == 0 && sig.length == 0, "UNSUPPORTED);

    IExchangeV4 nextProto = ...
    uint allowance = token.allowance(nextProto);
    if (allowance < amount) {
        // re-authorsize nextProto 
    }
    nextProto.deposit(token, user, token.balance(address(this));
    return true;
}
```

More advanced WithdrawalContract can use `data` and `sig` to call arbitrary third-party contracts.

**Comment by Brechtpd** [comment]
In 3.6 the user will already be able to call arbitrary contract calls for a withdrawal (implementation is deposit contract depended) so using this method of migration to a new version will simply be the same as interacting with any other smart contract. So I don't think we need to do anything for that really.

But having withdrawals/deposits for each users seems expensive and probably not really unnecessary. If we migrate from one version to another version I think it makes a lot more sense to just pre-populate the Merkle tree of the new version with the balance of all users of the previous version. This works out very well especially from 3.6 on because basically everything is stored in the Merkle tree anyway. Basically between versions we just keep the deposit contract, but fully replace the exchange contract in front of it. This means nothing needs to be transferred at all, and the migration can be made transparent because we can warn users before we do the swap, and everything in the new exchange contract is setup (with the correct initial Merkle root for the state of the previous exchange contract) before we do it so people can verify everything is correct. If they don't trust the process, they can just withdraw their funds themselves before the swap happens.

For 3.1 it's a bit more difficult because everything is more tightly coupled (in theory you could I guess use the full 3.1 exchange contract as the deposit contract for 3.6...). Though with some small contract changes (e.g. just allow withdrawing the full 3.1 exchange balance to the 3.6 deposit contract) I think it would also work out fine.

**Comment by dong77** [comment]
I'll close this issue then.
