### ISSUE TITLE
[Loopring 3.6] Make fast withdrawal module trustless

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1453]
We can make fast withdrawals trustless by:

- added a "fastWithdraw" function to the FastWithdrawalAgent. The method is only callable by the current exchange operator with a "WithdrawalReceipt parameter". The parameter will have the account address/id, token address/id, nonce, and amount.
- in ExchangeV3, we need to have a way to check if an address is or ever was an operator; we also need to provide a way to validate withdrawal receipt
- in FastWithdrawalAgent, we should provide a permissionless function 'verifyReceipt', if the verification fails, LRC will be paid from the exchange's owner staking to FastWithdrawalAgent as a penalty.
- FastWithdrawalAgent need functions to manages funds (deposit/withdrawal)

The downside: if an operator address is hacked, it may send invalid receipts to the FastWithdrawalAgent, and exchange staking will be drained.

I think a similar receipt validation/verification/penalty mechanism should be added for transfers as well.

**Comment by Brechtpd** [comment]
This is for a possible implementation of #1279, yes?

> in FastWithdrawalAgent, we should provide a permissionless function 'verifyReceipt', if the verification fails, LRC will be paid from the exchange's owner staking to FastWithdrawalAgent as a penalty.

If I understand correctly, this would allow us to collect funds from people, and we could make it trustless up to the value stored in the exchange stake. Using more funds than that would stop making it trustless and the operator can make a profit by draining the contract and not repaying anyone.

So I think there is kind of a problem of what this tries to solve. It doesn't make sense to me that the exchange stake will be that large a pile of money. Or better, it really shouldn't be because it has very little purpose being stored there. You can't do anything with it and it needs to be stored in LRC (I would expect a stable coin, or maybe ETH, to be used). If someone wants to implement such a mechanism I don't really see why they would choose to add a lot of funds to the exchange stake to make this possible. You can implement this mechanism with much more flexibility and freedom outside of the protocol. And I think with very good reason. This will be a large pile of money you don't just want to lock up for a long time for little reason. 

And even if the exchange stake is large pile of money, then it makes a lot more sense to let the operator use that pile of money directly, instead of indirectly by having a large exchange stake and then needing people to deposit an equal amount of money that can actually be used. This seems to make the liquidity problem twice as bad as far as I can see, we need the same amount of funds locked up in 2 places instead of just 1. 1 pile of money that can actually be used, another pile of money that's just sitting there for insurance.

> in ExchangeV3, we also need to provide a way to validate withdrawal receipt

Can be done externally.

> I think a similar receipt validation/verification/penalty mechanism should be added for transfers as well.

Fast withdrawals use transfers to repay the liquidity provider on layer 2 for efficiency. Fast withdrawals don't actually use any withdrawal mechanisms on the exchange itself.

**Comment by dong77** [comment]
First of all, we need to talk about receipts (#1279). If a receipt is sent to the user, we need a way for the users to verify receipts are valid, and if they are not, there should be a way to punish the relayer and/or pay the recipient (merchants/sellers). This applies to all kinds of receipts, otherwise, the receipts is centralized and we don't need to make it part of the protocol.

Receipt validation is similar to optimistic rollup, if a fraud receipt is found, we can:

- put the exchange to the withdrawal mode
- burn some of the exchange's staking or pay the user out of the exchange staking.

You are right that the max the relayer can lose in terms of asset is the staking (besides users and reputation). 
We should ask ourselves: **should we implement something like above for transfer receipts?**

If the answer is yes, we can then extend the implementation to fast-withdrawals, at least to reduce the trust between the relayer and liquidity providers -- One thing we need to realize is that when there are many tokens listed, the relayer may not have the fund to provide as fast-withdrawal liquidity, we can simply allow anyone to deposit tokens into the fast-withdrawal pool up to a limit set by the exchange owner/operator.

Now let's take a step back. Assume in the core protocol, we only provide a `function isReceiptValid(...) returns (bool)` function, no burning/punishment for invalid receipts. A trustless version of the TrustlessFastWithdrawalAgent can require the exchange ower to deposit some USDT/ETH as insurance which will be 100% transferred to the first address that can provide an invalid receipt. Once an invalid receipt was found, the TrustlessFastWithdrawalAgent stops working and all users who provided liquidity can withdraw their money. (I prover this approach instead of burning exchange staking)

A receipt is just a piece of information related to a particular request (trade, transfer, even change ownership) whose existence in the onchain data available can be verified onchain. Therefore, technically we can provide receipts for almost all types of requests.

**Comment by Brechtpd** [comment]
> We should ask ourselves: should we implement something like above for transfer receipts?
> If the answer is yes, we can then extend the implementation to fast-withdrawals

I don't think that's the case because they solve 2 different problems:
1. Receipts are used to guard users against an operator not doing a transfer. To do this, the operator needs to provide funds onchain as insurance.
2. Fast withdrawals use funds to immediately provide users with liquidity onchain. This also requires the operator to provide funds onchain.

So to solve 2), we would use the mechanism of 1), but this just moves where the operator needs to provide funds no? And then we require an external source to provide liquidity for the funds that will actually get used. I don't see how this helps in any way to provide the operator with extra funds that can be used for fast withdrawals because all funds used there need to be secured elsewhere also by the operator, or else the receipts don't work (see also below).

> Now let's take a step back. Assume in the core protocol, we only provide a function isReceiptValid(...) returns (bool) function, no burning/punishment for invalid receipts.

`isReceiptValid` can be implemented externally using `getBlockInfo`.

>  Once an invalid receipt was found, the TrustlessFastWithdrawalAgent stops working and all users who provided liquidity can withdraw their money. (I prover this approach instead of burning exchange staking)

I think either the operator can be trusted, or he can't be trusted and he just drains the contract completely in a single go. I don't think you can go around that. And if we would limit how much an operator can withdraw from the contract in a certain amount of time it kind of defeats the purpose of having the extra funds there at all. So I don't think we can allow the operator to withdraw more than what he can insure, which means no extra liquidity is provided to the operator using this mechanism.

> A receipt is just a piece of information related to a particular request (trade, transfer, even change ownership) whose existence in the onchain data available can be verified onchain. Therefore, technically we can provide receipts for almost all types of requests.

Sure, this possible using `getBlockInfo`.

**Comment by dong77** [comment]
As mentioned in https://github.com/Loopring/protocols/issues/1468, we are not going to implement a completely trustless FastWithdrawalAgent.
