### ISSUE TITLE
[LRC Staking] Redesign the LRC staking contract

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1454]
I have these ideas to improve the current LRC staking contract:

1. Use *index* to distribute staking rewards, so some time-based restrictions can be removed.
1. Do not sell tokens for LRC or Eth. Distribute multiple tokens to people who stake LRC. We need an *index* per token.
1. Each staking action and each withdrawal action will trigger a protocol fee withdrawal request -- the staking contract will query the list of tokens registered, then iterate through the list but simply withdraw the protocol in one token per action. 
1. All LRC protocol fees will be burned, all other tokens and ether will bel 100% distributed.

To encourage people to stay in the staking contract, we keep track of the following stats:

1. `amountEverStaked`, the total amount of LRC that has even been staked;
1. `amountStaked`: the current amount of LRC that has been staked;

When a user unstake `amount` LRC, assume the staking reward he can claim is `reward`, we apply a discount over `reward` calculated based on `amountEverStaked`, `amountStaked`, and `amount` such that the early the user unstake, the higher the discount will be. The user will be able to claim `reward * (1-discount)` as the actual reward, and `reward * discount` will remain in the protocol fee as reward to people who are still in the staking contract.

**Comment by Brechtpd** [comment]
> 2. Do not sell tokens for LRC or Eth. Distribute multiple tokens to people who stake LRC. We need an index per token.

Seems very expensive to have people withdraw multiple tokens to collect their gains!

> 3. Each staking action and each withdrawal action will trigger a protocol fee withdrawal request -- the staking contract will query the list of tokens registered, then iterate through the list but simply withdraw the protocol in one token per action.

Even more expensive! (Note that in 3.6 the operator can withdraw the protocol fees at any time, no onchain request needs to be made for that to happen).

Following the "eat your own dogfood"... We have this super user friendly mechanism to distribute profits to users on our rollup that kind of fits perfectly with staking. Very inexpensive and super low fees and super easy to understand. You buy it on the rollup and you get staking rewards, couldn't be simpler and easier to access. So if we don't use it, we have to compete with our own (I think superior) user experience where you can earn interest while you can still do whatever you want with it. LRC staking on layer 1 will have very high overhead costs with high gas prices, so only makes sense if you have a lot of LRC, otherwise you lose more money on transaction fees than you would ever earn, so we would probably lock out a lot of potential LRC holders. And we also need to make sure the interest earned is substantially higher than what we offer for other tokens because those will be much more flexible.

And if we can ever put LRC into another defi app so we can also interest on it like that... well where best to store your LRC. We would probably have to make use of it on the staking contract as well, because we probably want to offer it to users inside the rollup, and we can't really allow LRC inside our rollup to be better than LRC staking... 

So it seems to me there's lots of overlap! And we have to compete with our own product. :)

**Comment by dong77** [comment]
Closed. This topic will be discussed in the Team repository.
