### ISSUE TITLE
[Loopring 3.*] Allow amountS and amountB to be 0

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1467]
I think it's ok that we allow the amountS and amountB fields have zero values.

## if amountS == 0
the order's orderID must be 0 and trades that involve this order will not update tokenS's trade history subtree.
the order's signature can be missing and will not be verified in the circuits

## if amountB == 0
this is a regular 0-price order, all other properties are the same as a normal order's.

## WHY
We can use trades to implement red envelope, and maybe in the future we can use this to enable other use cases. I don't see how matching such orders will harm the system, unless the calculation of filledAmountS and filledAmountB will be complicated.

**Comment by dong77** [comment]
Brecht and I discussed this feature and decided to leave it as a low priority.

**Comment by Brechtpd** [comment]
I was thinking with 2**32 we could now use the account system as described in https://github.com/Loopring/protocols/issues/1401#issuecomment-659567235 to implement red envelopes, but this actually doesn't use a lot of accounts like I first thought, just 1 extra account/user:

- Create a dedicated "Red envelope" account for the payer. This account can be reused for all red envelopes the payer will ever create.
- Payer transfers some funds to his "Red envelope" account to share with people
- Payer shares the EdDSA keys for this "Red envelope" account with the platform distributing the red envelopes (or directly with potential payees). This allows the platform to distribute red envelopes with whatever logic/amounts it wants, and the operator cannot steal the funds.
- Anyone with the keys for the account can transfer funds out of the account (can be transferred directly to a new address)
- Unused funds can be transferred back by the payer from his "Red envelope" account to this main account whenever he wants

I think this is also a practical solution for implementing this, using no special features at all, just standard accounts + transfers to fixed addresses.

**Comment by Brechtpd** [comment]
If the red envelopes are distributed by a central party the payer may as well transfer the funds he wants to share to the platform's account and the platform just distributes the funds from that account as it sees fit with normal transfers. This is essentially what happens with these completely open orders or with the "Red envelope" account system when the EdDSA keys are shared with the central platform because the platform/operator can take all the funds anyway so there is no real difference.

So the separate "Red envelope" account scheme only really make sense when the platform/operator has no access to the keys. The payer shares the EdDSA keys only with the potential payees and the red envelope transfer signing logic is executed locally in the payee's app. If that's not the case, just transfer to the platform's account and you're done because that's the same thing. :)

**Comment by dong77** [comment]
I see the points, but I think using additional accounts as red-envelope accounts will introduce some extra account management logic for the wallet backend (not a from a zkRollup perspective). So I think using the dual authoring transfer may be simpler overall.
