### ISSUE TITLE
路印协议3.6设计内部反馈 / Internal feedbacks and discussions regarding 3.6

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1468]
反馈如下：
The following feedbacks regarding Protoco 3.6's design and implementation are collected:

### 挑战/Challange

一个用户可以给无限多个未注册的地址小额转账，比如0.1个LRC，而几乎无需付费。这种情况下，1600万账户也可能很快用光。如何防止这种攻击？

Evil users may transfer tiny amounts of tokens to many new addresses using EdDSA signatures. How can we prevent this from happening so our account nodes are not wasted due to Sybil attacks?

### 方案/Solution

我们需要确保每个offchain请求都支持费用，如果请求的结果是一个新的账户node被占用，我们就要对这个请求收费用。或者如果offchain请求不支持费用设置，那么对于那些造成新账号被占用的请求，中继就要拒绝服务。

We need to make sure all types of offchain requests support fee settings, so if a request ends up with a new account node being used, we will charge some fees; if the fee is too small, the relayer will reject the request. If a request type does not support fees, the relayer will reject all the requests of such types that consume account nodes.

### 补充说明/Other Info

zkSync‘s account space is 2^24. And it only allows two scenarios to create a new account. One is through deposit, another is transfer_to_new.

### UPDATE
We will use 32 bits as accountID so we will support over 4 billion users eventually. See https://github.com/Loopring/protocols/issues/1463

## 2. 所有offchain请求都需要增加validUntil / Applying `validUntil` to all offchain requests

see https://github.com/Loopring/protocols/issues/1209

## 3. 需求上是否考虑在提现中支持多种token一次签名 / Allow force withdraw multiple tokens using one layer1 tx

See https://github.com/Loopring/protocols/issues/1251 and https://github.com/Loopring/protocols/pull/1466

### UPDATE
The feature is not supposed to be used by users, we decided to do nothing.

## 4. 支持订单中的amountS或amountB可以等于0 / Support amountS/amountB to be 0

如果用trade来发红包，我们希望订单里面可以支持amountB/amountS的一个为0，或者都为0。我们还希望如果一个订单的amountB是0，那么该订单无需owner的签名就可以生效，且该订单的orderID也必须是0，并且不改变任何交易历史。

We hope the amountB/amountS in orders can be both zero. Then we can use one order and several trades to implement a red envelope. Removing the `amountS/B!=0` check may enable other future use cases. Besides, we also need to make sure if the `amountB == 0`, the order does not need the owner's signature, the orderID must be 0, and the tokenS's trade history won't be modified when such an order is used.
 
See issue: https://github.com/Loopring/protocols/issues/1467

### UPDATE
Decided to leave it feature as low priority

### 挑战/Challange

中继会对一些请求按照数量锁定资产，这部分资产就无法通过链下请求被使用。但是如果锁定的资产因为tokenIndex的原因变得不合理，那么就需要重新设计锁定的逻辑。

The relayer currently locks the user's asset for orders, withdrawals, and transfers, so these locked assets are not available for new orders/withdrawals/transfers. Assume the to-be-locked amount is A, the relayer will check if the current L2 balance is >= A, if so, A is locked, and there are `balance - A` available. But if the deposit contract takes a big loss and the token index becomes much smaller, the already locked amount A may become invalid, as the actual L2 balance may now < A.

### 方案/Solution

Do not support a deposit contract that may take a loss. Make sure the new tokenIndex is always bigger than the previous one.

### UPDATE
Brecht and I decided to remove index from the core protocol.

## 6. 收据如何证伪 / Receipt verification

We need to find a way to efficiently prove a transfer/withdrawal receipt is valid/invalid. The idea I have is to provide a receipt with the following information:

- the numeric ID of the block (`blockID`) where the request is processed
- the offset of the request data in the calldata
- the request data to check against the calldata

To prove the inclusion of the corresponding request, the caller must provide the data (whose hash will be calculated and check against the dataHash), and the receipt, exchange contract will verify on-chain.

### 挑战/Challange

The challenge is that **the relayer is unable to tell the transfer recipient the `blockID`** due to many potential reasons (for example ##7)

### 方案/Potential Solution

In each block, we add two more fields, `startRequestId`, and `endRequestId` such that `prevBlock.endRequestId + 1 == thisBlock.startSequenceId`.When someone wants to verify this recipient, he will easily find out which block is supposed to include the request, then provide that `blockID` to the verify method.

This is assuming the relayer can tell the transfer recipient immediately what the sequence number for his payment transfer in the block, which may also be challenging.

### Update：
It seems we have found a solution, see https://github.com/Loopring/protocols/issues/1279#issuecomment-662805027

## 7. 链下请求的链上验证依赖 / Offchian request validation using onchain data

Now the protocol supports validating offchain requests using onchain ECDSA signatures and tx hashes. This means there is L2-to-L1 dependency.

### 挑战/Challange

An ECDSA signature may be valid when the relayer is about to process the request, but may become invalid in commitBlock. Take hebao smart wallet contract as an example, if a wallet requests a transfer using ECDSA and then locks the wallet, then the ECDSA verification onchain will fail, and the relayer may find it's too late... If an tx approval hash is found onchain, but the corresponding transaction may get reverted while the relayer is proving the block that includes the request, then the relayer will also have to re-org the block...

### 方案/Potential Solution

- For ECDSA signatures, the relayer should only support such requests signed by EOAs, not by contract addresses;
- For tx approve hashes, the relayer has to wait for 12 confirmations to accept the corresponding request -- put the requests in a queue

## 8. 快速提现的中心化解决 / Do not go trustless for fast withdrawals

We have come to the conclusion that we only want a trust-based fast withdrawal solution, instead of a withdrawal-receipt-based (fraud-proof based) trustless solution. But we do need the flexibility of accelerating all kinds of offchain withdrawals that we pick.

## 9. 同一个token是否可以注册多个资产 / 1 token =>many tokenIDs

Suppose in the future we want to allow people to trade Ether on Loopring, and Ether-in-Maker (mETH) as well. Then maybe we should change the IDepositContract to:

```

    function deposit(
        address from,
        address token,
        uint8      tokenScheme, // <<- NEW
        uint96  amount,
        bytes   calldata auxiliaryData
        )
        external
        payable
        returns (uint96 actualAmount, uint tokenIndex);

    function withdraw(
        address to,
        address token,
        uint8      tokenScheme,, // <<- NEW
        uint    amount,
        bytes   calldata auxiliaryData
        )
        external
        payable;

```

such that Ether means (address=0x0, scheme=0), and mETH means (address=0x0, scheme=1). 

We then need to make sure token registration also supports the scheme parameter.

**AFTER a second thought, we can simply create a contract to manage mETH, it will mint mETH token to people who deposited ETH, and if someone returns mETH, it burns it and returns ETH**, 

BUT WAIT,  if the above idea is correct, why don't we the interest/loss between ETH/mETH entirely inside that contract. Such that tokenIndex is not visible to layer2?

### Update
We have decided not to support DeFi integration as part of the core protocol.

**Comment by Brechtpd** [comment]
> The relayer currently locks the user's asset for orders, withdrawals, and transfers, so these locked assets are not available for new orders/withdrawals/transfers. Assume the to-be-locked amount is A, the relayer will check if the current L2 balance is >= A, if so, A is locked, and there are balance - A available. But if the deposit contract takes a big loss and the token index becomes much smaller, the already locked amount A may become invalid, as the actual L2 balance may now < A.

You can always lock a balance at a certain point in time if you know where it is included in a block. The index is only updated by processing a deposit request with an updated index, any newer indexes in other places do not matter to the relayer, it only needs to check the indexes in account 1. So even if there are additional losses afterwards, it does not impact amounts used in transactions before such a deposit with newer index is processed, and so only the remaining `balance - A` amount would be subject to further losses/profits. Because all transactions can now be done chronologically inside a block I don't think this will be problem because the relayer knows exactly where it will be included in a block?

**Comment by Brechtpd** [comment]
> The challenge is that the relayer is unable to tell the transfer recipient the blockID due to many potential reasons (for example ##7)

Is this still the case in 3.6? (not sure what the link should point to)

> When someone wants to verify this recipient, he will easily find out which block is supposed to include the request, then provide that blockID to the verify method.

I don't think that can work because the recipient of course wants the receipt to fail so he can receive extra funds. The receipt needs to contain the rules where the transaction will be so they cannot be manipulated in any way and we can depend on them onchain. In theory this could contain a range of multiple blocks, but that will of course be more expensive. But these receipts can be updated when needed so perhaps good enough to start with.

**Comment by dong77** [comment]
## Regarding 'index'
How do we support the trading of cDAI (Dai in Compound)? cDAI is an ERC20 token, we can support it in 3.1 without 'index'. If we create some deposit contract to earn money for the user's asset, we should also mint some other token so people holding them can come back to claim the original assets. We can choose to auto-deposit the newly minted token to our exchange if we want, but we don't have to. The point is: supporting index is not necessary in Loopring :) Problem solved :)

**Comment by Brechtpd** [comment]
> The point is: supporting index is not necessary in Loopring :) Problem solved :)

I think you're right! We can get close to the current index system by just doing it on the UI level. The UI can just show `amount = MerkleTree.amount * (depositContract.balance / depositContract.totalDeposited)`, because that's the amount that the users will get when they withdraw. And for deposits they will get an "index corrected" amount of tokens in the Merkle tree: `MerkleTree.amount = deposit.amount * (depositContract.totalDeposited / depositContract.balance)`. Well, something like that, the index is baked into the balance put inside the Merkle tree so every unit of balance inside the rollup has the same value.

It's of course not completely the same because the balances do not track the underlying value automatically inside the rollup (which is the only purpose of the index). Users will need to sign transactions with amounts that are different from what they see in the UI. And it's not possible to sign transactions using the underlying value so the value of the amount signed by users will change with time (the same as with cTokens I guess). At some point the balance 100 DAI in the Merkle tree could actually be worth 102 DAI, and some time later it could be worth 103 DAI, even though the user only signed a transaction for 102 DAI. 

So some minor differences... but seems close enough and keeps things simpler. :) So looks like we should drop the index!.

> We can choose to auto-deposit the newly minted token to our exchange if we want, but we don't have to.

Not sure what you mean with that? You mean claim the interest gained on the amount put into defi by the deposit contract? Then yeah sure, it has always been up to the deposit contract on how to make use of that.

**Comment by dong77** [comment]
I think we can completely remove the *index* concept away from the core protocol. Please see: https://github.com/Loopring/protocols/issues/1329#issuecomment-662792795
