### ISSUE TITLE
[Loopring 3.6] Give a much larger value to ForcedSlots in shutdown mode

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocols#1500]

**Comment by Brechtpd** [comment]
If we set the number of slots available onchain to something we are sure the operator is able to process, how does shutdown mode impact this number and why does it suddenly increase?

Do we expect forced withdrawals to be used more often in shutdown mode? Personally I believe they will never be used, they are just there for security. Even in shutdown mode I see very little reason why they would be used because the operator will just cooperate and do withdrawals for users as usual, there's nothing to be gained for the operator by not doing so if he is able.

**Comment by kongliangzhong** [comment]
In case that the exchange will not do anything in shutdown mode, in this case, only a very limited amount of force-withdrawals can be submitted.

**Comment by Brechtpd** [comment]
Sure, but if the operator wants to be difficult he just doesn't enter shutdown mode anyway. The risk for users is the same when the exchange is shutdown or is not shutdown, we can't expect the operator to act faithfully before calling shutdown either. The risk for the users is the same, shutdown mode is only there for operators that do want to play nice.

The operator can even ask a higher fee for the withdrawal when not using forced withdrawals (which is costly for users because it costs gas), so if he is forced to do the withdrawals anyway it would make more sense to just do offchain requests for both users and operator, I don't see any reason why he would wait on users to do the forced withdrawals if the operator still wants to do them.

**Comment by kongliangzhong** [comment]
> Sure, but if the operator wants to be difficult he just doesn't enter shutdown mode anyway.  

If the exhcange operator doesn't enter shutdown mode, he will not be able to withdraw the exchange-staked LRC. 
If the operator doesn't want to get its staked LRC back, he may not do anything and just let the exchange goto withdraw-mode. So my point is: If the slot value is small in shutdown mode, then a bad operator can get its stake back by doing very limited work.

**Comment by Brechtpd** [comment]
> then a bad operator can get its stake back by doing very limited work.

I think this is fine and is inevitable if the rollup has many users. There will always be a limit in how much withdrawals the operator will have to do, how big of a percentage he is forced to do depends on how many users are in the rollup and how many tokens they have. If there are a lot of users with a lot of tokens he will still only be forced to do an extremely small small numbers of the withdrawals. Does it matter if he is forced to do 0.1% of all withdrawals or 0.01% of all withdrawals?

If we force the operator to be able to process 10x the forced withdrawals in shutdown mode then the operator needs to make sure he can do that. So why not always force him to do 10x the forced withdrawals? That makes the exchange safer in general because if the operator is malicious people always can get their money out faster, not just in shutdown mode, which would be a win-win.

But I think all of this is a pretty theoretical because I don't see this being used at all. Like in 3.1 we have this pretty complex way to force operators to do onchain requests as quick as possible. But exchanges want to do that anyway even without the smart contracts forcing them to do so because they want to keep their users happy. These exchanges are run by businesses that have a lot more to lose than just the exchange stake, so I don't think the exchange stake is the main factor that drives good behaviour. I believe we can assume operators are acting in good faith, and in the worst case we can't really make it very good any way, so it just needs to be good enough because that scenario has extremely little chance of actually happening.

This is of course an very simple change so if you really want it we can add it, but I don't think it matters if the normal number of forced slots is high enough (which should be the case regardless of this).

**Comment by kongliangzhong** [comment]
> if the operator is malicious people always can get their money out faster
Ok, I think this is reasonable. Let's keep the contracts as simple as we can.
