### ISSUE TITLE
[Loopring 3.6] Remove approveOffchainTransfer function in IExchangeV3.sol

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocols#1501]
we can always use approveTransaction instead, which is much cheaper.

**Comment by Brechtpd** [comment]
It is indeed just a helper function, but we'll have to make sure we can do what's done there in a utility/library contract if needed.

Why would it be much cheaper though? For functionality like the fast withdrawals with transfers, all the work done in `approveOffchainTransfer` would probably still be done, but just in the fast withdrawals contract. I guess you could pre-compute the hash and approve it like that in some cases (though not exactly great to just send the tx hash unrelated to the other data), but that won't always work because the on-chain logic may directly impact what kind of transaction needs to be approved. The main cost is the storage write + contract call, the hashing/storage reads are only a small-ish part of the total cost.

**Comment by kongliangzhong** [comment]
A little cheaper, i think, because the calldata size is smaller.

**Comment by kongliangzhong** [comment]
> Why would it be much cheaper though? For functionality like the fast withdrawals with transfers, all the work done in `approveOffchainTransfer` would probably still be done, but just in the fast withdrawals contract. I guess you could pre-compute the hash and approve it like that in some cases (though not exactly great to just send the tx hash unrelated to the other data), but that won't always work because the on-chain logic may directly impact what kind of transaction needs to be approved. The main cost is the storage write + contract call, the hashing/storage reads are only a small-ish part of the total cost. (could even be more expensive if tokenIDs need to be fetched from the exchange contract from somewhere else).

Yes, I agree. From an interface perspective, approveOffchainTransfer function is duplicated with approveTransaction function in functionality.
