### ISSUE TITLE
[Loopring 3.6] code review for `processConditionalTransactions`

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1502]
For the code below. Can we:

1. use `txAuxiliaryData.length` directly without even providing `numConditionalTransactions` in data
2. move the 4 bytes for  `operatorAccountID` in front of the bytes for `numConditionalTransactions` so skipping `operatorAccountID` can happen outside of `processConditionalTransactions`
3. Currently, we need rollupMode to process all withdrawals, this doesn't seem to be right. It also means we cannot support the Validum mode because all deposits and withdrawals are considered to be *conditional transactions*. Maybe we can simply remove the `rollupMode` parameter completely and enforce the rollup mode.

```solidity
function processConditionalTransactions(
        ExchangeData.State          storage S,
        uint                                offset,
        bytes                        memory data,
        ExchangeData.AuxiliaryData[] memory txAuxiliaryData
        )
        private
        returns (uint blockFeeETH)
    {
        // The length of the auxiliary data needs to match the number of conditional transactions
        uint numConditionalTransactions = data.toUint32(offset);
        offset += 4;

        if (numConditionalTransactions > 0) {
            require(S.rollupMode, "AVAILABLE_ONLY_IN_ROLLUP_MODE");
            // TOTOD(daniel): ...

            // Cache the domain seperator to save on SLOADs each time it is accessed.
            ExchangeData.BlockContext memory ctx = ExchangeData.BlockContext({
                DOMAIN_SEPARATOR: S.DOMAIN_SEPARATOR
            });

            require(
                txAuxiliaryData.length == numConditionalTransactions,
                "AUXILIARYDATA_INVALID_LENGTH"
            );
            // TODO(daniel): use txAuxiliaryData.length directly

            // uint32 operatorAccountID = data.toUint32(offset);
            offset += 4;
            // TODO(daniel): move operatorAccountID ahead and move it out of this method.
```

**Comment by Brechtpd** [comment]
>     1. use `txAuxiliaryData.length` directly without even providing `numConditionalTransactions` in data
> 

We can't. We need to make sure we process the exact amount of conditional transaction onchain as the circuit expects. Otherwise we could simply skip signature verification in the circuit and just not process the transaction onchain to do transactions without any approval from the users. `txAuxiliaryData.length` can be chosen completely by the operator if we don't verify it against the expected number.

>     2. move the 4 bytes for  `operatorAccountID` in front of the bytes for `numConditionalTransactions` so skipping `operatorAccountID` can happen outside of `processConditionalTransactions`

Fine with me, but doesn't it make sense to do it where it is now? If we don't have any conditional transactions we don't have to parse it becaus we'll never use it, if we have conditional transactions in theory it could be required to process the conditional transaction onchain.

>     3. Currently, we need rollupMode to process all withdrawals, this doesn't seem to be right. It also means we cannot support the Validum mode because all deposits and withdrawals are considered to be _conditional transactions_. Maybe we can simply remove the `rollupMode` parameter completely and enforce the rollup mode.

You're right, didn't think of removing it here and just left it in from 3.5. I'm pro removing Validum mode because we won't use it anyway. The only difference with rollup mode is that we would zero-out the DA data when the transaction isn't a conditional transaction.

**Comment by dong77** [comment]
I'm OK for removing Validum mode completely, which will further simplified the code, although not by much.
