### ISSUE TITLE
[Loopring 3.6] code review DA encoding and decoding

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1503]
Currently, the exchange data is not structured, so we have many `data.toXXX(offsite)` reads. Should we use `abi.decode(data, RollupData)` instead?  

For auxiliary data of each transaction (take withdrawal for example), we have this:
```solidity
 WithdrawalAuxiliaryData memory auxData = abi.decode(auxiliaryData, (WithdrawalAuxiliaryData));
```

**Comment by Brechtpd** [comment]
Standard ABI encoding is pretty wasteful because it adds a lot of zeros. This is no problem with the auxiliary data because zeros are cheap and will be compressed away (and is also not used for the most scalable transactions like trades/transfers). But this is a big problem for the DA because in the circuits all these zeros do need to be passed through SHA256 which will be very expensive.

There is `abi.encodePacked` which doesn't do the padding, but there is no `abi.decodePacked` which can revert to the original struct (this would even be impossible when containing dynamic arrays with how it currently works). So if we would want a function like that we'd have to write it ourselves. Perhaps we can write a function that can do packed -> unpacked so we can use abi.decode, but that doesn't seem to be that much easier because it would need some meta information about the struct we'd have to write manually. Or we could use code generation for this (or even the complete decoding), but that makes things much more complex in the background.
