### ISSUE TITLE
[Loopring_3.6] code review optimize submitBlocks

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1504]
Maybe we can organize the blocks offchain in a way so the contract doesn't have to find and group the same type/size of the blocks. The relayer can do it off-chain and the contract can simply process blocks based on the instructions from the operator. That will save some gas for sure.

**Comment by Brechtpd** [comment]
Not against it, though I did some measurement when I wrote the code for 3.5 and it doesn't end up saving a lot of gas and makes the interface less clean. In the normal case all blocks will be the same block type and size so the code won't need to actually loop, so the only overhead is perhaps some extra data copies because we would still have to validate the inputs.

Steve [suggested](https://github.com/Loopring/protocols/pull/1307#discussion_r461079762) the same thing a couple of days ago. My reply:
> Blocks need to be processed sequentially, so if the order in which the blocks need to be committed differ from which they can be batched more efficiently than there always needs to be some re-ordering, re-mapping or extra input validation, it just depends on where you do it or where you take the cost. We could do things slightly differently here to save some gas, but then submitBlocks would be much less clean than it is now, so I think it won't be worth it.

> We could also just require that all blocks that are submitted can all be batch verified together, but that makes some scenario's less efficient.
