### ISSUE TITLE
[Loopring_3.6] enable to validate receipt signatures

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1507]
We want a signed receipt from the change operator verifiable even if the exchange changed its owner. Therefore, in LoopringIoExchangeOwner contract, we may need to implement EIP1271 and make sure all signatures from old/deprecate operators can still be verified.

**Comment by Brechtpd** [comment]
>  make sure all signatures from old/deprecate operators can still be verified.

In some cases it is useful to simply stop accepting signatures from a previous operator when e.g. the operator keys were hacked.

I think it may make more sense to not directly couple receipts to all operators in `LoopringIoExchangeOwner`. A receipt should be the responsibility of a single operator. If there are multiple operators, they will want to have their own receipt/insurance contract, otherwise they are directly effected by the others. If the operator cannot promise he will include the tx in a block himself he shouldn't provide a receipt promising to do so to begin with. And if the receipt cannot be used by the user then the user shouldn't accept it.

**Comment by dong77** [comment]
From the protocol's perspective, validating a receipt should not include the checking of signatures or whether the signer was/is the exchange operator. The signer/signature verification should be part of the challenge/response game, and the protocol just needs to provide a way to verify if a receipt's corresponding tx is included in some block.

**Comment by dong77** [comment]
"the protocol just needs to provide a way to verify if a receipt's corresponding tx is included in some block."

@Brechtpd I don't think we have a function in IExchangeV3 for validating a receipt yet (I'm not talking about the challenge/response game)

**Comment by Brechtpd** [comment]
There's only `IExchangeV3.getBlockInfo` which can be used in an external contract to verify a receipt. I don't think there's a reason to do the actual receipt validation inside the exchange contract.

**Comment by dong77** [comment]
I added some extra comments to that function.
