### ISSUE TITLE
[Loopring_3.6] review: using 1/10000 as the unit of fee bips

### ISSUE THREAD

**Issue by hosschao** [Loopring/protocols#1565]
We use 1/100000 in smart contract and 1/10000 in circuit. Should use 1/10000 in both sides.

**Comment by dong77** [comment]
@Brechtpd I didn't know this. If this is the case, we can easily change the smart contract to match the circuit?

**Comment by Brechtpd** [comment]
`1/100000` is only used for the protocol fees In both circuit and smart contracts, because the value needs to be very small. The range is 0.001% to 0.256% using just 1 byte.

For trading fees the unit is `1/10000` and the range is 0.01% to 0.64% (only 6 bits are used for these, need to be put into the DA for each order).

So making the protocol fee also use `1/10000` would greatly limit the usable range in which it can change because it will never be higher than ~0.1%. Making everything `1/100000` might make more sense, but than we waste more bits on the DA of orders. 

This was done to optimize for the expected values and so we can save on bits/costs.

**Comment by dong77** [comment]
Brecht, I think using `1/10000` for protocol fees should be fine. The current protocol fee is 0.06% (6 bps), and we will probably reduce it to 2 or 3 bps, but not to a value smaller than 1 bps. That said, I'm not proposing to change it to 1/10000 now UNLESS there will be a  great reduction in data cost, and I don't believe it's the case.

**Comment by Brechtpd** [comment]
That's right, it won't make any difference in costs. It's now 2 bytes/block, and it would remain 2 bytes/block, it's never a cost per tx so in any case it never really matters. The only difference is the range and the minimum step size.

**Comment by dong77** [comment]
@hosschao Shall I close this issue?
