### ISSUE TITLE
[hebao_1.1] reduce Store storage cost

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1579]
1. Change
```solidity
 struct Guardian
    {
        address  addr;
        uint     group;
        uint     validSince;
        uint     validUntil;
    }
```
to
```solidity
 struct Guardian
    {
        address  addr;
        uint64     group;
        uint64     validSince;
        uint64     validUntil;
    }
```

2. Change 
```solidity
    struct Quota
    {
        uint    currentQuota; // 0 indicates default
        uint    pendingQuota;
        uint64  pendingUntil;
        uint64  spentTimestamp;
        uint    spentAmount;
    }
```
to
```solidity
    struct Quota
    {
        uint128 currentQuota; // 0 indicates default
        uint128 pendingQuota;
        uint64  pendingUntil;
        uint64  spentTimestamp;
        uint128    spentAmount;
    }
```

**Comment by Brechtpd** [comment]
> ```solidity
>  struct Guardian
>     {
>         address  addr;
>         uint64     group;
>         uint64     validSince;
>         uint64     validUntil;
>     }
> ```

This will still take up 2 storage slots (20 + 8 + 8 + 8 > 32). I think this can be further reduced without any problem to a single storage slot like this (20 + 4 + 4+ 4 == 32):
```
struct Guardian
{
     address  addr;
     uint32     group;
     uint32     validSince;
     uint32     validUntil;
}
```

**Comment by dong77** [comment]
Yes, it can, but sometimes I feel uncomfortable with uint32. It gives the impression that this contract has a really short lifetime to other parties.

**Comment by Brechtpd** [comment]
A max lifetime up to 2106 is short, in crypto? :) I certainly wouldn't think so, I'm pretty sure even if funds would still be stored there (and Ethereum is still alive) everything would have been stolen already because lots of the cryptography we currently depend on would have already been broken well before then. :) These crypto things aren't made to last more than a couple of decades at most, 128 bit security won't last forever.

Could also do something like this I guess to make it last much longer, but anything longer than a couple of years is pretty theoretical I think:
```
struct Guardian
{
     address  addr;
     uint16     group;
     uint40     validSince;
     uint40     validUntil;
}
```

**Comment by dong77** [comment]
done
