### ISSUE TITLE
[Loopring_3.6] reduce DA by enforcing the same operator account for all txs in a block

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1590]
It seems we can use different operator account for different transactions in a block. Maybe we can reduce the DA by only allowing all txs to use a single operator account?

**Comment by Brechtpd** [comment]
There can only be a single operator for the complete block, and we only put the operator accountID in the DA a single time for the complete block.

There is some discussion about how to update the balances of the operator in https://github.com/Loopring/team/issues/100, but this only impacts the number of constraints/tx. But for the operator account his would even more (and dirtier) workarounds then what we currently need for the protocol fees account like explained in https://github.com/Loopring/team/issues/108 (because the account could be used in even more transaction types, unless we limit that), so I chose not to do it because it won't make that much of difference.
