### ISSUE TITLE
[Loopring 3.6] Implement a Managing Contract for Loopirng Layer-2 AMM Liquidity Pool

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1677]
In this issue, I'd like to outline a few design objectives of the layer-1 managing contract for our AMM liquidity pool accounts on  L2. These objectives are based on a discussion in the Shanghai office and my updated understanding of the new AMM support in our circuits.

## Objectives

1.  Allow users to add liquidity to and remove liquidity from the managing contract on L1. ERC20-based liquidity tokens can be mint or burnt. The liquidity tokens may be transferrable and can be deposited to L2 if the token is registered.

2.  Allow regular L2 accounts to add liquidity to the AMM account by using L2 transfers. On L1, the correct bookkeeping should be done or liquidity token should be mint to the owner. These add-liquidity transfers' data must be delivered to the AMM managing contract before the corresponding block is submitted. *As of now the operator's behaviors are not guaranteed by the protocol and is more of a centralized trust on the relayer [see the possible solution below]. If the relayer doesn't notify the managing contract of these add-liquidation transfers, then the user will not get his share of the pool, and his fund will be lost.*

> One possible solution is to make the managing contract enforce an opening AmmUpdate tx and a closing AmmUpdate tx, and all non-trading AMM account balance update txs must be wrapped by these AmmUpdate tx pairs (no other tx can be put in between these AmmUpdate pairs of course). By doing this, the managing contract will not miss any liquidation addition and removal no matter the requests are on L1 or L2. (note, this doesn't seem to require us to change the current implementation)
>
> If the operator doesn't put all transfer-based, L2 liquidation addition/removal txs between the pair, there will be data inconsistency in the AmmUpdate pair because all those txs must add up.

3. Allow L2 accounts to remove liquidity from AMM account back to the user's L2 account via a transfer. The transfer will be created by the relayer without any signature, and it will be validated by the managing contract on L1 to create a hash-based approval. If the operator refuses the request, the L2 account may choose to interact with the managing contract to force a withdrawal, this should be very similar or even exactly as point 1.

4. Allow users to deposit **one single token** to the AMM account by modifying the weight. *This is more of a constraint instead of a desired feature*.  As shown in the AmmPool.sol file, Liquidity addition and removal on L1 can keep the weights unchanged, but if we use transfers on L2, then it's very hard to make sure the users will sign the right transfers fast enough - while the UI presents the liquidity-related transfers to the user, the AMM pool is constantly being used for matching and the actual balances of tokens may change. As a result, layer-2 liquidity transfers to/from AMM accounts will be inacurate.

> From the product's perspective, we can still try to maintain near-constant weight ratios among different AMM token balances. But the weight values themselves will change.

5. Allow a user who added liquidity on L1 to burn his liquidity tokens to 1) get back his assets directly on L1, and 2) get back his assets in his layer-2 account (a new account will be created if necessary); also allow a user who added liquidity on L2 to get back his assets on either L2 or on L1, all in one single request.

6. Allow the operator of the exchange to charge a fee in ETH for handling join/exit transactions.

**Comment by Brechtpd** [comment]
> 2. ... If the operator doesn't put all transfer-based, L2 liquidation addition/removal txs between the pair, there will be data inconsistency in the AmmUpdate pair because all those txs must add up.

I'm not sure I understand this solution correctly. I think the transfer can be done by the operator not between the expected AmmUpdates. What data will be inconsistent so this can be detected? Weights will remain the same after the transfer, balances are continuously modified because of of trading. I think 3+4 will be necessary and solves other problems as well.

> 4. But if we use transfers on L2, then it's very hard to make sure the users will sign the right transfers fast enough - while the UI presents the liquidity-related transfers to the user, the AMM pool is constantly being used for matching and the actual balances of tokens may change. As a result, layer-2 liquidity transfers to/from AMM accounts will be inacurate.

I don't think this is any more of a problem than the current L1 deposit/withdrawal method. The user doesn't need to sign a simple "transfer 1 ETH from account X to account Y" to use L2 transfers in the pool contract. What the user signs can be very similar to what deposit/withdrawal now does, so for deposit a list of max amounts of all tokens in the pool to deposit and the expected pool tokens in return. So once the relayer ends up processing the L2 deposits to the pool contract it simply checks if the current balances are still valid for the request, if not it's dropped (for uniswap the Ethereum tx would fail). So I don't think there's any reason to update weights unless desired by the user/curve itself.

5) Should be easy enough if we support both L1/L2 methods any way.

**Comment by dong77** [comment]
There might be something we have to do on the protocol level to enable AMM pool assets to be only transferred ONCE instead of twice per join/exit. The current deposit function must involve an actual ERC20 transfer; we can allow users to transfer the tokens beforehand to our DepositContract and a new type of Deposit request will only need to consume these token balances, without the actual ERC20 transfers.

With such support, AMM tokens don't have to hold any tokens at all.

**Comment by Brechtpd** [comment]
## Joining the pool

### Normal offchain transfers for joining the pool

I currently think this is definitely a possibility. People just sign normal transfers to the pool and sign the transfer with EdDSA.
If we change it so that transfers can only be done to accounts with zero AMM weight we can force the operator to call the correct callback function. Because only the pool contract can set the weights of the pool account to 0 and then set them back to enable the pool again. So the operator is forced to do the transfers between those AMM updates, and these transfers are checked by the pool contract.

We still have the problem that the amounts the user signed may not match directly with the actual balances in the pool. But the pool contract can just allow some slippage on the pool tokens the users gets compared to the amounts transferred (which the user knows beforehand so by doing the transfer to the pool account approves this). If the slippage on the ration is too great when the operator tries to include the transfers in a block the operator just drops the transfers and asks the user to sign new transfers (though of course the hope is that this doesn't happen in normal cases because the ratio of the balances in the pool will remain largely the same).

Transfers don't always include the account owner address in the transfer DA (but does always contain both accountIDs), the address is only included for conditional transfers to save gas, but perhaps we can also allow the operator to include in the DA when he requests it even for normal transfers. Or maybe just the accountID of the sender is good enough, depends on what we end up needing in the pool.

### Approved offchain transfers for deposits

Instead of the user signing normal transfers, the user signs something like this with his Ethereum keypair:

```
struct JoinRequest
{
    uint poolAmountOut;
    uint96[] maxAmountsIn;
}
```

This has guards against slippage built in (and can be set as required by the user) and the user only needs to sign a single request no matter the number of tokens in the pool.

The pool just verifies the signature of this request and calculates the amounts that need to be transferred for the latest pool balances, and then just approves the `n` L2 transfers as needed. This will be more expensive than the method above (~3,000 gas to check the signature + `n` * 5,000 gas to approve the transfers), but it is more accurate and a bit more flexible (and doesn't need additional constraints on when transfers to the pool contracts are allowed).

## Exiting the pool

The pool contract needs to approve all transactions done on its account, so we always need at least approve thins things onchain.

In all coses the liquidity tokens need to be locked into the pool contract so we can burn them when the pool callback is called in a deterministic manner. In most cases however I would assume (especially for layer 2 only users) these liquidity tokens won't be moved (or will rarely be moved). So instead of minting these tokens to the user directly, we simply mint the tokens to the pool contract itself so they remain locked up by default. The user can then request to unlock these if he wants to move these, but this will only be possible after a small delay (or something similar, many options available here).

- Transfers can be used to exit immediately to layer 2. This may seem more expensive at ~5,000 gas/approved transfer, but otherwise we need to keep track of all the balances of users on layer 1 which is likely to be even more expensive!
- Withdrawals can be used to exit to layer 1 (method currently used in the test contract). Here we have the choice again to withdraw to each user directly or just withdraw to the pool contract and keep track of users' balances in the pool contract. Here withdrawing to the pool contract + bookkeeping the pool contract will be cheaper.
