### ISSUE TITLE
[Loopring 3.6] AMM pool can be a taker in a trade

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1695]
With the current implementation, two AMM pools can swap tokens in a trade, so one is a taker, and the other one is a maker. This allows all AMM pool accounts to reach a very close spot price without additional asset for cross-pool arbitrage. If we remove this "feature", we'll reduce tx circuit size by ~3.5%. Brecht and I think maybe we should keep it as a feature.

> Brecht, is it possible for an AMM pool to be the taker while a regular order is the maker in a trade?

**Comment by yueawang** [comment]
One case might confuse people that normally in an exchange maker fee is less than the taker's, e.g. current our maker fee is 0. If AMM is taker, a MAKER_ONLY use order then deals with it, so the user pays AMM fee rather than 0 maker fee. Not a big problem I think, but the trader needs to be educated if this case happens.

**Comment by dong77** [comment]
I don't think we should expose this feature to the end-users. Maybe just us it to adjust the prices of different pools.
