### ISSUE TITLE
[Loopring 3.6] Questions on AMM price check in SpotTrade and AmmUpdate circuit

### ISSUE THREAD

**Issue by yueawang** [Loopring/protocols#1702]
In SpotTrade, the circuit checks the price change, and asks for "priceBefore <= priceAfter" as below. Is this check necessary? In what situation it would fail?
![image](https://user-images.githubusercontent.com/26989346/92301988-e093b500-ef9a-11ea-8bb8-044ba832023c.png)

Another question is: In the AmmUpdate circuit, should we check if the AMM price stays still or almost still considering the precision after weight change?
Thanks!

**Comment by Brechtpd** [comment]
> In what situation it would fail?

It could happen if the power approximation is inaccurate and the approximation error makes the trade cheaper instead of more expensive. In my (not that extensive) testing with approximation errors I've only seen the price get more expensive than required by the curved, never less, but I can't say that's always true. Balancer does the same kind of approximation and also does these checks, which is why I added them as well.

> In the AmmUpdate circuit, should we check if the AMM price stays still or almost still considering the precision after weight change?

I don't think the protocol can make any judgement on this. It's the account owner that'll have to make sure weights are updated in a sensible matter depending on what the purpose of the weight change is.

**Comment by yueawang** [comment]
> I don't think the protocol can make any judgement on this. It's the account owner that'll have to make sure weights are updated in a sensible matter depending on what the purpose of the weight change is.

Is account owner the AMM contract? You mean the contract knows how to adjust the weight and approve the corresponding request on-chain? Does it make the contract more complex? Thanks!

**Comment by Brechtpd** [comment]
> Is account owner the AMM contract? 

Either the account owner is an AMM pool contract or just a normal user.

> You mean the contract knows how to adjust the weight and approve the corresponding request on-chain? Does it make the contract more complex?

_Only_ the contract knows how to adjust the weights, I don't really see how the protocol could even do it in a general way. Depending on what the goal is the contract can be very simple (fixed weights) or quite complex (use oracles to modify the weights in specific ways).
