### ISSUE TITLE
[Loopring 3.6] Allow layer-2 initiated AmmUpdate transactions?

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1721]
I'm assuming that there will be reliable third-party off-chain price oracles (signed with well-known signers). Then on layer-2, we can allow the update of weights at a much higher frequency based on these oracles -- the layer-2 contract can verify the oracle's timestamp and signature. If we do this, our AMM will offer better liquidity efficiency and reduce impermanent loss. 

A simple solution is probably to allow arbitrary `bytes` auxiliary data for _AmmUpdate_ transactions and the protocol just forwards the data to the managing contract for interpretation.

**Comment by Brechtpd** [comment]
If I understand correctly, I think this is already possible just by using the normal onchain signature check + ERC1271 to validate the AmmUpdate tx. This will allow the pool contract to authorize arbitrary updates using whatever logic it wants without having to go through the block callback. I'm not sure that's exactly what you mean because this will still use layer 1 smart contracts for the actual authorization check, so not fully layer 2.

**Comment by dong77** [comment]
I think we should change 
```solidity
    // Auxiliary data for each AMM update
    struct AmmUpdateAuxiliaryData
    {
        bytes  signature;
        uint32 validUntil;
    }
```

to 
```solidity
    // Auxiliary data for each AMM update
    struct AmmUpdateAuxiliaryData
    {
        bytes  signature;
        uint32 validUntil;
        bytes   data
    }
```

so that `data` can be used to bring L2 oracle related data to L1 for verification.

**Comment by Brechtpd** [comment]
`bytes  signature` can contain any data the target contract can interpret as it wants because it's just a piece of data sent to the contract to authorize the other data sent (there's no need for it to be an actual signature if that doesn't make sense). I think this is how ERC1271 is expected to be used.

**Comment by dong77** [comment]
Then I propose to change the name a bit. I'll create a PR for it.

**Comment by dong77** [comment]
It seems the AmmPool contract doesn't have access to AmmUpdateAuxiliaryData at all, `bytes signature` included. We need to be able to include layer-2 oracle data inside `AmmUpdateTransaction.AmmUpdate` instead of `AmmUpdateAuxiliaryData` (my previous suggestions doesn't work)

**Comment by Brechtpd** [comment]
> It seems the AmmPool contract doesn't have access to AmmUpdateAuxiliaryData at all, bytes signature included.

It gets it via ERC1271? With ERC1271 the contract gets the hash of the transaction  + the "signature" which can contain any data we want. So if the contract needs to check that the weights are updated correctly following some rules than that'll work fine as far as I can tall (contract gets balances + new weights to set). We simply put all the data the contract needs in the signature bytes array. And if a signature is defined as "showing that some data is correct" than that works as well.

> The other idea is to add a bytes field inside AuxiliaryData in AmmPool - then it has nothing to do with the core protocol.

That works as well. The AmmPool can also just have an extra function which can be called at any time and which just takes in the oracle data and approves the necessary AMM update transaction on the exchange contract. Because it's just a simple isolated update transaction there's no real need to go through the callback mechanism.

**Comment by dong77** [comment]
I see. Thank you.
