### ISSUE TITLE
[Loopring 3.6] fail faster in block submission

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#1735]
As of now, if we don't wait for long enough and a deposit transaction get re-orged out of a block, our block submission will fail. But since the failure is deep inside its corresponding process() function, there will be a lot of gas wasted.

I think for each block, we can add some extra checks to make sure a block-level precodition must be true before we process each transaction. One such precondition is the hash of the last known block that contains at least one onchain request.

**Comment by dong77** [comment]
https://github.com/Loopring/protocols/pull/1736/files

**Comment by Brechtpd** [comment]
> As of now, if we don't wait for long enough and a deposit transaction get re-orged out of a block, our block submission will fail. But since the failure is deep inside its corresponding process() function, there will be a lot of gas wasted.

In most cases the largest part of the gas cost is the calldata (especially when disregarding the proof verification, which is done after all the block checks), so if the invalid blocks gets onchain we will already paid most of the gas we will end up paying for the blocks (unless the block contains a lot of withdrawals or needs to do a lot of onchain verifications). The invalid block getting onchain in any capacity is already costly and should be avoided (also it's pretty bad on the UX level because it can potentially revert transactions for users).

I think this should be detected by the relayer well before we even create the Ethereum tx. There's also lots of other logic like `validUntil` which can fail blocks, so I think it's inevitability up to the relayer to keep track of all this, lots of things that can go wrong which aren't always easy to check early onchain. Even if we don't wait for any confirmations for the deposit, the deposit will still just have been included in a block waiting for more transactions to fill up the block (there's no benefit to the user to get the block containing the deposit onchain as fast as possible). And then the block still needs to be proven as well, which likely takes up at least another couple of minutes. So there should be enough time to catch these things offchain (of course something can slip through the cracks on the relayer level, but then that seems like something that should be fixed).

**Comment by dong77** [comment]
Talked to relayer engineers, my proposal is unnecessary, same reason as Brecht mentioned above.
