### ISSUE TITLE
[Loopring AMM] Join/Exit fees

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocols#1831]
For joins we can now only request fees in one of the tokens in the pool. For exits we can't request a fee on L2. Maybe makes more sense to just define a single fee token + fee amount for joins/exits so a fee can be paid in any token? For joins we can just use the first transfer to the pool account, for exits we use the transfer from the LT to the pool account.

**Comment by dong77** [comment]
Since all joins are on L2 and the relayer can reject invalid/small join requests, I would suggest that we don't charge any fee for joins. Joins are more like makers, we don't charge makers either.

For exits, I think we can still apply fees on layer2 transfers using the same token. Fees can be deducted from the original transfer amount and the smart contract can verify `fee + transferAmount` isAlmostEqualTo `amounts[i]`.  But we can apply a global exit fee as a percentage so we don't have to specify the fee amount in the call data to reduce gas cost.

**Comment by Brechtpd** [comment]
That also works.

> But we can apply a global exit fee as a percentage so we don't have to specify the fee amount in the call data to reduce gas cost.

I'm not really a fan of a fixed percentage here because the amounts people withdraw will widely differ and the main goal of these fees should be to pay for the gas cost and nothing else (and high fixed percentage withdrawal fees would be a good reason for LPs not to deposit to our pools because they may want to move funds around a lot). Calldata cost is low enough and will be insignificant with all the other costs that I don't think we should worry about that here.

**Comment by dong77** [comment]
Then let's charge a fix amount of the first/last token as the fee.

**Comment by Brechtpd** [comment]
Can you explain a bit more, not sure I fully understand your last comment. :)

**Comment by dong77** [comment]
Joins: no processing fee as the operator can ignore some join requests if the amounts are too small.
Exits: use the last token in `tokens` as the fee token then charge a fixed amount as the processing fee.

**Comment by dong77** [comment]
Implemented in this PR: https://github.com/Loopring/protocols/pull/1873/files
