### ISSUE TITLE
[Loopring 3.6] Deposit refund logical change

### ISSUE THREAD

**Issue by hosschao** [Loopring/protocols#1833]
As far as I know, in case which A deposit to B. If relayer doesn't handle (and decides never handle) this request, only B could get back the token of this deposit tx.

It seems that A should be the right guy who could receive the token of deposit tx since he is the owner of the origin token.

Is there any reason for this behave?

**Comment by dong77** [comment]
I thought A is able to withdraw the fund, not B. @Brechtpd can you confirm?

**Comment by Brechtpd** [comment]
If A deposits to B than B owns the deposited funds in all cases. I think that makes sense, regardless of if the relayer processes the deposit or not, I don't see how that matters (and is out of the control of the sender). To do a layer 1 -> layer 2 transfer, you would use a deposit (and you can count of B having received the funds), the fact that it's not available immediately on layer 2 I think shouldn't matter.

I don't really see a use case why the original sender would remain in custody of the funds until the deposit is processed. Could you give a scenario where the origin sender remaining in custody of the funds is the behavior that is expected?

**Comment by dong77** [comment]
Brecht, if we wire money in the banking system to someone and the bank rejected or failed the transfer, the fund should still belong to the original owner. People may have the intuation that the money is only gone if and only if the transaction went through.

Giving the sender the power to claim back the fund from failed transactions will also make the sender feel confortable to try another transaction. Using layer-2 transfer as an example, if it fails, the user simply try another transfer, without worring about the previous fund is now owned by the recipient. And this example also shows that some type of failed transactions will not be able to transfer fund ownership to the desired recipient. 

We should follow users' expecitation and intuition.

**Comment by Brechtpd** [comment]
So I think the current behaviour is what people expect? 

A user deposits to the account of someone else and this Ethereum transaction is valid and successful. There is no failure or rejection here and everything went as expected. There is no need to retry anything or any reason to retry anything. Funds were successfully moved from one user to another, which is what the sender wanted.

The sender expects the recipient has received his funds (successful Ethereum tx) and doesn't need to keep monitoring if the funds are actually made available on layer 2 for the recipient account. Which would be a strange thing to expect of the sender, and he would have to keep monitoring/trying until the relayer makes it available on layer 2 for all the different users he sent funds to, which he can never be sure will actually happen so he just pays the gas cost and hopes for the best? This can hardly be the expected behavior from users.

I don't see why it matters if it's made available on layer 2 or not for the recipient, this is out of the hands of both the sender and recipient, introduces periods of uncertainty because it's not an atomic operations any more, and I feel shouldn't matter because the only difference is which "wallet" the recipient receives the funds.

**Comment by Brechtpd** [comment]
Same reasoning is followed for `to` for withdrawals btw. If the withdrawal transfer isn't done, the new owner of the tokens is `to`, not `from`. Doesn't make sense to me to give those tokens back to the previous owner so he needs to withdraw again himself and send them to the destination address again. If the withdrawal token transfer hasn't been done for some reason anyone can still send those tokens to `to`.

**Comment by dong77** [comment]
Let me use an example and focus on user experience
I'm supposed to send you some tokens to your layer2 account, I choose to use my layer1 account as the source, so it's actually a Deposit (from both users' perspective,it's a cross-layer transfer), then somehow the deposit failed. Now, I will tell you the transfer failed, and you have to do something to get the fund from my failed transactions. Your user experience will be terrible. 

I believe it's the sender's duty to make the transaction go through, if not, try again.

**Comment by Brechtpd** [comment]
> I'm supposed to send you some tokens to your layer2 account, I choose to use my layer1 account as the source

I guess this is where we see things differently. I only see it as a transfer from one account to another account because the sender can never guarantee it will get to layer 2 so it's a losing battle. If the sender explicitly promises funds on layer 2 he should do so with a layer 2 transfer.

> then somehow the deposit failed

I still believe nothing has failed! And hard/slow for the sender to find out if it has "failed".

> Now, I will tell you the transfer failed, and you have to do something to get the fund from my failed transactions

Not really true, the receiver doesn't really have to do anything, **anyone** can call `withdrawFromDepositRequest` and send the funds to the user's layer 1 wallet. If the sender is so concerned for the recipient he can call it as well when the deposit hasn't been processed by the relayer. Sure, funds are in the user's layer 1 wallet and not in the user's layer 2 wallet, but don't see much of problem with that. Seems strange the funds *have* to be received on layer 2 in all cases, and see it as "failed" otherwise.

> Your user experience will be terrible.

I'm not saying any of the options are perfect, both options have problems. But I think having the receiver be the owner of the funds directly is the less bad one. Keeps things simple and immediate and the number of places that someone needs to check for funds owned by himself is actually very limited:
- If the recipient is in control there's not a lot of places it can be in: Layer 1 wallet, Layer 2 wallet, pending deposits and approved withdrawals for the user's account. And there already needs to be a UI for pending deposits for the user's own account because deposits done by himself can already remain pending as well. So receiving funds from someone is exactly the same as that.
- If the sender remains in control, there will need to be a map like [from][to], which will spread the funds of the sender over all different senders. Harder to track onchain and needs a special UI to know which layer 1 -> layer 2 deposit was not processed so it can be tried again.

> I believe it's the sender's duty to make the transaction go through, if not, try again.

The sender can make the transaction go through on layer 1.

> The receiver should not keep scanning incoming failed transactions and claim those funds.

As written above, a deposit not being processed is not a special case and funds in pending deposits are just one of the few places the user can have funds. Approved withdrawals work very similarly and we don't think the UI where the user needs to claim a withdrawal is terrible? Not perfect of course, but nothing out of the ordinary. And much easier to track than doing it the other way where funds for a single user can be spread out in unlimited ways.

> The receiver's wallet may be very simple, and in some cases, the receiver will simply rely on some notifications for successfully transfers to deliver goods, no time spent on failed transaction claiming.

If the wallet is that simple than it can only support layer 2 transfers and so the sender should send on layer 2. But I don't think such a simple wallet will work very well because it won't support many interactions that are necessary regardless of how this special case is handled.


But seems like this discussion is pretty theoretical. :) Regardless what we think is correct, having the sender remain in control will make things more complex in the smart contracts and the UI. So even if we want to change this behavior (which I still very much don't think is a good idea!) will it be worth that extra complexity?

**Comment by dong77** [comment]
I did some analysis of changing the behavior, the change will definitely make deposit handling more expensive. So lets keep things as they are, but I'll create a PR to add a "from" field to `DepositRequested` event.
