### ISSUE TITLE
[circuit 3.6] How to set storageId to a forceWithdraw?

### ISSUE THREAD

**Issue by lydy** [Loopring/protocols#1942]
![image](https://user-images.githubusercontent.com/21301076/96971776-2e16b200-1548-11eb-8f83-31c506900c0d.png)

nonce require: storage.data=0
ifrequireSameStorageID required: storageId==accountA.storage.storageId

How to set it except 0?

**Comment by Brechtpd** [comment]
The relayer can use any `storageId` in the storage tree of the account as long as it passes the nonce check. Maybe some confussion between `storage.data` and `storage.storageId`?

I can make it more flexible for the relayer by not requiring the nonce check to pass, so that will reduce the requirement to any `storageId`. Better and only a minor change, I'll make a PR.

**Comment by Brechtpd** [comment]
There could indeed be a problem here, fixed in #1949
