### ISSUE TITLE
Redesign and implement LRC staking pool

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#2021]

**Comment by Brechtpd** [comment]
I was starting the implementation of a simple contract, but @mfinestone mentioned L2 staking again, like he always does. :)

What if instead of a staking contract, we just distribute the rewards to all users that hold LRC on L2 just like we do for all other rewards? The relayer takes snapshots and then we distribute the LRC rewards on L2 at some fixed interval.

This is similar to how we tackle other rewards, and so this will save us a lot of work: no contract needed, no special UI in the smart wallet/web, cheaper for users,  easy to explain to users, helps on-boarding to L2, ...

Because of the flexibility we could even experiment with more advanced rules if we would ever want them (e.g. maybe even give protocol fee rewards to users that hold LRC in an AMM pool, or higher rewards for LRC that hasn't been moved for a long time).

This does not prevent us from creating more advanced vaults in the future that perhaps make use of LRC in other ways, the rewards can always be split fairly between all different "vaults" by checking the LRC balance in each.

**Comment by mfinestone** [comment]
:). I'm glad my incessant mentioning of this finally hit home. Thanks!
