### ISSUE TITLE
UniswapV2PriceOracle uses reserves to determine the price

### ISSUE THREAD

**Issue by pauliax** [Loopring/protocols#2056]
https://github.com/Loopring/protocols/blob/47969503aab749c0b8a9ff2078a64b226f931ab7/packages/hebao_v1/contracts/price/UniswapV2PriceOracle.sol#L44-L54

I am curious why you decided to use the pair reserves, not the cumulative-price when determining the price? The reserves can be temporarily increased or unbalanced with the help of flash loans so as far as I know the recommended way is to use cumulative-price variables as these are harder to manipulate: https://uniswap.org/docs/v2/core-concepts/oracles/

**Comment by Brechtpd** [comment]
Good point. Although as far as I understand it needs some extra work to make this work, and so probably has support for less tokens out of the box (e.g. https://docs.uniquote.finance/). Because we now cache the prices the gas price is less of a concern. Better price data is always a win of course. 

On the other hand, I think this manipulation isn't that big a deal for our specific use. Even if the price is manipulated by a large percentage like 20% for a short amount of time, this is really just a normal day in crypto. And because the price data is only used for the daily quota that should be okay I think.
