### ISSUE TITLE
[Protocol3] provide onchain price oracles based on settlement history 

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#210]
Loopring DEXes should have the ability to provide onchain price oracle based on trading history either independently or combinedly (which is more reliable and less manipulatable). Such price oracles can be used to enable leverage trading and crypto lending. 

A special circuit design is needed to force DEX to post correct price stats on a regular basis and in a timely manner if the DEX opts in such feature.  

In this issue we can discuss 1) if we need such a feature and if so 2) how to design and implement it

**Comment by dong77** [comment]
Calculating moving average settlement prices might be expensive onchain. Maybe we can do it in circuits and only publish the data onchain.

**Comment by Brechtpd** [comment]
Running over all trades onchain will be more expensive than doing it in circuit. I think we'll need an additional Merkle tree that will accumulate all prices for all token pairs tokenA/tokenB or token/some baseToken. This Merkle tree could maybe contain moving averages for different time frames and maybe some extra data so the prices can be combined over Exchanges.

With a max of 256 token there can be ~256^2 markets so that's a lot of data. Just storing a Merkle root onchain I think would make the most sense. Someone can then use a Merkle proof to make the price for a specific tokenA/tokenB available onchain at some interval. This way there's no cost for making data available onchain for markets nobody is interested in, but all data could be made available if needed.

If we limit the available data to a single base market (ETH or DAI) we could perhaps just make all prices available for that base token, though this still could be quite expensive to for each block depending on how much data this is, so we'd probably still want to limit this somehow.

**Comment by dong77** [comment]
Maybe we should limit this feature to only trading pairs that use ETH as the quote token, i.e., LRC/ETH, to reduce computation and tree updates. Then we can have a new tree or a subtree to store the latest moving average of each token involved. This might be the simplest solution. We probably want to make sure the DEX can opt-in to push the price data on-chain at the protocol level so other dApps can use them, probably with a fee, to calculate another price over time as their DeFi price oracles.
