### ISSUE TITLE
[AMM] Support adding liquidity for one token by modifying the weights.

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#2111]

**Comment by Brechtpd** [comment]
Unless we do something with oracles like Bancor previously did (which well, didn't really work), adding liquidity for one token to the pool in Balancer doesn't modify the weights (LPs that were already in a 50/50 pool don't want to suddenly be part of a 90/10 pool because of the very different properties).

I'd have to check to be sure, but I think for balancer it's practically the same as first just swapping the one token for the others and then adding all of them to the pool. If this is indeed the case, it doesn't seem like we should add any special logic to the pool contract because swapping is so cheap so users won't even really notice, so it would just be a UI thing.
