### ISSUE TITLE
[Loopring3] potential security issue: withdrawal may be manipulated by malicious operators

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#215]
> The following is from @lyddream 
 
According to current protocol design, when an onchain-withdraw/offchain-withdraw block being created and successfully proved by our circuit, a malicious operator can change the withdrawal amount and then commit it to Ethereum blockchain, and this block can still be verified by the proof generated from the circuit.  After this block had been verified and set to the finalized state, the wrong withdrawal amount is used in the following distributions.  In this way, a malicious operator can steal users tokens, which they should not able to do so as DEX operators.

**Comment by Brechtpd** [comment]
This should not be possible. All data sent by the operator (merkle roots, withdrawal data, DA data, ...) is hashed [here](       https://github.com/Loopring/protocols/blob/24e2f7c31d0d1676f208a3dd8a26e2d8508fde17/packages/loopring_v3/contracts/impl/libexchange/ExchangeBlocks.sol#L336). This hash is used as the public input for the verifier together with the proof. Only when this hash matches exactly with the data calculated and hashed in the circuit is the block valid.

The operator cannot freely choose which data to send onchain, all this data is checked against what the circuit expects using that hash, otherwise the the verifier will not accept it.

**Comment by dong77** [comment]
Confirmed this is not an issue. I'm closing it.
