### ISSUE TITLE
[Loopring 3.6] Anchored AMM pool

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#2232]
For ETH-USDT pool, uniswap's pool is much bitter. Assume they have X eth and Y USDT, and we have x ETH and y ETH. In your equation we can config to have two values Dx (delta x) and Dy, their value is X and Y at time T1. And our pool fomular is 

```
(x + Dx)*(y + Dy) = K.
```

On a regular basis, we syncup with Uniswap to change：

```
Dx = X - x or 0 if X <x
Dy = Y - y; of 0 if Y < y
```

The result of such change is that we have a similar price impact with a smaller range of settlement.

When users swap, we just need to make sure the settlement amount is smaller than what we have in the pool.

**Comment by Brechtpd** [comment]
I think this is basically the same mechanism that other protocols have tried to achieve "liquidity amplification" like Bancor v2.0 and Dodo, where an external price is used to change the curve to provide much better slippage. But there are problems with that, and Bancor even moved away from this mechanism (I don't know about Dodo as of know).

If I understand correctly, this can be very bad for LPs because an impermanent loss is turned into a permanent loss because of the price that always changes. If you take a snapshot at some time with an external price and keep using that internally, that price is quickly out of date and so trading happens at a potentially very large volume at a "wrong" price. Eventually the external price is checked again and the pool balance is restored. This requires balancing the pool at this new "correct" price, basically making the impermanent loss permanent by realizing the loss each time this is done.
