### ISSUE TITLE
BAMM Simulation and Discussion

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#2254]
I use this script for to simulate BAMM, it seems the computation is not complicated. @Brechtpd , please take a look.

https://github.com/dong77/bamm_simulation

**Comment by Brechtpd** [comment]
Wrote some code starting from uniswap (and balancer) because I'm more familiar with that it's more how we do things now:

```
class BAMM {
    constructor(F) {
        console.assert(F >= 1);
        this.F = F; // amplification factor
        this.x = 0; // virtual balances
        this.y = 0;
        this.Rx = 0; // actual balances
        this.Ry = 0;
        this.feeBips = 30;
    }

    add(dx, dy) {
        this.x += dx * this.F;
        this.y += dy * this.F;
        this.Rx += dx;
        this.Ry += dy;
    }

    getAmountOut(amountIn, reserveIn, reserveOut) {
        let amountInWithFee = amountIn * (10000 - this.feeBips);
        let numerator = amountInWithFee * reserveOut;
        let denominator = (reserveIn * 10000) + amountInWithFee;
        let amountOut = numerator / denominator;
        return amountOut;
    }

    buyY(amountIn) {
        let amountOut = this.getAmountOut(amountIn, this.x, this.y);
        this.x += amountIn;
        this.y -= amountOut;
        this.Rx += amountIn;
        this.Ry -= amountOut;
        console.assert(this.Rx >= 0 && this.Ry >= 0, "out of bounds");
        return [amountIn, amountOut];
    }

    buyX(amountIn) {
        let amountOut = this.getAmountOut(amountIn, this.y, this.x);
        this.y += amountIn;
        this.x -= amountOut;
        this.Ry += amountIn;
        this.Rx -= amountOut;
        console.assert(this.Rx >= 0 && this.Ry >= 0, "out of bounds");
        return [amountIn, amountOut];
    }

    toString() {
        return `F = ${this.F}, x = ${this.x}, y = ${this.y}, Rx = ${this.Rx}, Ry = ${this.Ry}, p = ${this.price()}, k = ${this.k()}`;
    }

    k() {
        return this.x * this.y;
    }

    price() {
        return this.y/this.x;
    }
}
```

If I didn't make any mistakes, basically everything remains the same except joins/exits which need to multiple or divide by the amplification factor. And in a smart contract there wouldn't even be any need to store local actual balances because transfers would simply fail if the curve is out of bounds. But for the circuits we would have to store both somehow, and I think that will be no problem because we can do exactly that in our Merkle tree: we can store the actual balance in `balance` and the virtual balance in `weightAMM`.

Also, it would be cool if multiple different curves (like with different amplification factors) could be active in the same pool (e.g. a standard curve and one with an amplification factor, and the LP token received contains the type of curve so exits can try to do the reverse). I think this should be fairly simple with only like 2 simple curves, but fees will be hard and may not be worth it compared to just trading against a bunch of different separate pools.

**Comment by dong77** [comment]
I also beleive the aggregation of different pools with the same tokens & different amplification factors can be done outside of the pool.

I also think it's OK to removet the support of different weights in the curve for simplicitiy's sake.

**Comment by dong77** [comment]
I think there is a bug in your `add` function. Adding/removing liquidity should not change the price. And you also need an `remove` function.

**Comment by Brechtpd** [comment]
> I think there is a bug in your `add` function. Adding/removing liquidity should not change the price. And you also need an `remove` function.

Oh yeah, I did not implement joins/exits correctly (or any LP tokens), `add` function just there to do whatever I wanted to setup the pool. But except for the added amplification multiplication all current code we currently have remains the same, the difference is very small.

> I also think it's OK to removet the support of different weights in the curve for simplicitiy's sake.

Could indeed simplify the code. We'd need to store the virtual balances somewhere and we could remove the power function.

**Comment by dong77** [comment]
One thing I don't like in my implementation is this: Alice joins the pool with 100USDT and 0 USDC, Bob joins the pool with 0 USDT and 100 USDC, they get the same amount of LP tokens. Then if Alice/Bob exits, she/he will get 50USDT and 50 USDC without paying any fees, but in fact they just did a (partial) swap...

**Comment by Brechtpd** [comment]
This is what balancer does: https://docs.balancer.finance/core-concepts/protocol/index#single-asset-deposit-withdrawal

Just a swap basically, so I don't think we should make joins/exits more complicated because it will end up doing the same thing as a swap, so just exposing this on the UI which does the swap in the background makes sense to me if we want to allow that.

**Comment by dong77** [comment]
https://github.com/Loopring/protocols/pull/2432
