### ISSUE TITLE
A problem in MathGadgets

### ISSUE THREAD

**Issue by zerochl** [Loopring/protocols#2469]
I found no bool check in AndGadget and some other Gadget.

```

class AndGadget : public GadgetT
{
  public:
    std::vector<VariableT> inputs;
    std::vector<VariableT> results;

    AndGadget( //
      ProtoboardT &pb,
      const std::vector<VariableT> &_inputs,
      const std::string &prefix)
        : GadgetT(pb, prefix), inputs(_inputs)
    {
        assert(inputs.size() > 1);
        for (unsigned int i = 1; i < inputs.size(); i++)
        {
            results.emplace_back(make_variable(pb, FMT(prefix, ".results")));
        }
    }

    const VariableT &result() const
    {
        return results.back();
    }

    void generate_r1cs_witness()
    {
        pb.val(results[0]) = pb.val(inputs[0]) * pb.val(inputs[1]);
        for (unsigned int i = 2; i < inputs.size(); i++)
        {
            pb.val(results[i - 1]) = pb.val(results[i - 2]) * pb.val(inputs[i]);
        }
    }

    void generate_r1cs_constraints()
    {
        // This can be done more efficiently but we never have any long inputs so no
        // need
        if (inputs.size() > 3)
        {
            std::cout << "[AndGadget] unexpected input length " << inputs.size() << std::endl;
        }
        pb.add_r1cs_constraint(ConstraintT(inputs[0], inputs[1], results[0]), FMT(annotation_prefix, ".A && B"));
        for (unsigned int i = 2; i < inputs.size(); i++)
        {
            pb.add_r1cs_constraint(
              ConstraintT(inputs[i], results[i - 2], results[i - 1]), FMT(annotation_prefix, ".A && B"));
        }
    }
};

```
A = 1, B = 2, result() will return 2, maybe this is right in C++, because if num is more than 1, the num == true is ok.
but, in ZKP and as base gadget, less the boolean check, whether ok?

**Comment by Brechtpd** [comment]
We don't always check all inputs because often this is unnecessary overhead of checks already done elsewhere. For some gadgets, like these that only really make sense for boolean inputs, we depend on the caller of the gadget to only pass in valid inputs.

**Comment by Brechtpd** [comment]
We're only really interested in the security of the complete circuits, so our gadgets are only used with a limited set of inputs because a lot of checks on these inputs are already done elsewhere. Sure, we could add extra constrains everywhere, but that would mean we would add a lot of additional unneeded constraints which increases the prover complexity. There are many gadgets that only work correctly under certain specific inputs. We have statements written for our gadgets, specifically for the `AndGadget` the inputs are required to be boolean:
https://github.com/Loopring/protocols/blob/master/packages/loopring_v3/circuit/statements.md#and-statement

**Comment by zerochl** [comment]
if enforce_bitness = false, it does not increase the complexity of the circuit. I mean, base gadget should be perfect.
Loopring is in a leading position in ZKP, maybe some other will use your code directly, maybe will cause an accident.
