### ISSUE TITLE
[Protocol3] Add unit tests for UserStakingPool

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#266]

**Comment by adamchen0510** [comment]
Hi, Dong:
There is a question I'm not sure it's an issue or not.
In this condition:
User A staked 1000 LRC and the reward is 10 LRC after 90 days.
1 If A withdraw all 100LRC first and then claim, it would not claim any token as user.stake already 0 after withdraw. The final LRC of A is 100.
2 If A claim first and then withdraw all LRC, then he can get 110 LRC.

In https://github.com/Loopring/protocols/issues/208:
`function withdraw(uint64 amount) {
    claimReward();  // always claim reward first
    ...
}
`
It would claimReward first in withdraw, but now it's missing.
So I'm not sure it's by design or not.

**Comment by dong77** [comment]
@yueawang I found bugs in the implementation. Please

**Comment by dong77** [comment]
Tested
