### ISSUE TITLE
[protocol3] Enable scalable post-deployment capacities (aka. extendable Merkle tree)

### ISSUE THREAD

**Issue by letsgoustc** [Loopring/protocols#294]
Right now we hard code Account tree depth is 20. So the maximum supported accounts are around 1 million. But in the very beginning, we may have accounts only around 10000, so can we design an extendable solution to handle it?

**Comment by dong77** [comment]
By "extendable" do you mean we can easily deploy a new set of smart contracts on the target blockchain without modifying the code? 

The depth-configuration of the tree (account sub-tree depth, token sub-tree depth, and history sub-tree depth) will affect the genesis hash which is a constant variable.  We can provide a deployment script to calculate the genesis hash based on the depth-configuration and use the depth-configuration together with the computed genesis hash as inputs to deploy the contract.

Once the depth-configuration is chosen and the protocol is deployed, it is really hard, but not impossible, to make a change to the depth-configuration. Allowing increasing the depths of one or more sub-tree might be possible but this requires a specific circuit to handle it. For example, if we change the depth of token sub-tree from N to N+2, then we can make the original subtrees as the left-most sub-trees of the "extended" new sub-trees and assuming all other new siblings are 0s.  Then this new circuits can calculate a new root tree hash based on this assumption. After a second thought, this might be very nice feature and make a DEX really scalable in user/token/order capacity.

**Comment by letsgoustc** [comment]
Yes, by "extendable" I mean we we don't need to modify the code on chain. As long as we need to extend, we can create another new contract automatically to continue or even only modify merkle root calculation dynamically even without any new contract.

It's doable because we can switch circuit according to some data on chain. For example, we have a variable to indicate the current tree depth in SmartContract, and relay engine can read the value to select the corresponding circuit to generate verify.

**Comment by dong77** [comment]
This is doable but non-trivial. We have to take into consideration the fact that our protocol may have many DEX instances. We cannot expect all those DEXes to switch to new depth-configurations at the same time. That means the protocol may have to support a set of different depth-configurations and allow any DEX to opt-in new configurations with large sub-tree depths.

Let's assume the 3 depth configurations are: `A(accounts), T(tokens), H(history)`. Then we may enable the protocol to support A = 20,21,22, T=10,12,14, H=10,15,20, then we have 27 combinations (let's call the schemes) and for each scheme, we need a whole new set of verification keys to support different block sizes.

An alternative approach is to enable a set of depth-scheme such as:
scheme1: A=20,T=10,H=10
scheme2: A=21, T=12, H=20
This will limit the number of schemes but is less flexible which I really don't like.

**Comment by dong77** [comment]
@kongliangzhong @Brechtpd  Going forward, maybe we should use a mapping to locate a verification key like the following:

```
key = verificationKeys[accountDepth][tokenDepth][HistoryDepth][blockType][blockSize];

```

**Comment by Brechtpd** [comment]
I think this adds a lot of complexity for not a lot of performance gain.

The cost per account level (remember that we use a Quadtree so each level increases the number of leafs by 4x) with Poseidon for the trade circuit is
```
2 accounts * 
2 paths (verify+update) * 
250 constraints (cost per Merkle tree level) 
= 1,000 constraints / Quadtree level
```

So if we decrease the number of accounts by 16x (max `2^16 = 65536` accounts, a very low number) we save just 2,000 constraints. The same delta is true if we increase the number of accounts by 16x, we have an extra cost of 2,000 constraints. So just setting the account tree depth to 24, a 16x increase of the number of accounts compared to the current depth of 20, we increase the cost by only 2000 constraints. `2^24 = 24M` accounts should be more than enough.

There is also a small increase in the data we need to store for data-availability for larger account addresses (24bit compared to 20bit). But we can store this in a way to make use of the cheaper cost of zero bytes in calldata when a smaller number of accounts is actually used, so this will also only very slightly increase the cost for DA, while still supporting a very large number of accounts with the same circuit when needed.

I would say let's just use large enough maximum values, otherwise we have an explosion of circuits/contracts we have to maintain (and test) and do trusted setups for.

**Comment by letsgoustc** [comment]
Brecht mentioned the maintain and test effort is a good point. If we can just simply set the maximum number with acceptable circuit constraint, it's okay for me. With quad-tree optimization, it looks like we can increase the tree depth now. I suggest the depth parameter can be A:22, T:12, H: 12. We don't need too much trading history record.

**Comment by Brechtpd** [comment]
A bit of a side note, but the way we store the trading history now is a balance between cost of constraints, cost of data-availability and decentralization. The other option would be to store the trading history in a different tree which is completely independent of the account tree.

By making the trading history part of the account Merkle tree (which we currently do):
- Cheap trading history updates (depth of the tree is not high at all)
- Better decentralization because no extra data is needed for an operator to start trading an a DEX. All trading history is put onchain which allows anyone to update the trading history without having to trust on anyone else to share this data (if an operator doesn't have the trading history data he cannot update the trading history, which stops him from committing any trades).
- But some extra data (the orderID, so about 5 bytes, though this data will contain a lot of cheap zeros normally) needs to be put onchain so that everyone can rebuild the Merkle tree (critical for withdrawal mode).

By making the trading history a separate tree:
- More expensive history updates. The depth of the tree needs to be high enough so there are no collisions, or needs to be high enough to emulate how we currently do it with order IDs
- Less decentralized because if there are multiple operators the trading history needs to be shared offchain somehow.
- Cheaper DA because we don't need to put any trading history (orderIDs) data onchain.

I think we still want to use the current method even though the operator will be centralized for the constraints savings (and thus the lower proof generation cost). But with #289 (maybe with some minor modifications like passing in the blockIdx) we can actually do the separate tree as well in the future:
- A circuit is made that does all trading history updates in a new Merkle tree (this Merkle tree can have any structure).
- The block contract stores the trading history Merkle root onchain. The only extra thing we need to check in this block contract is if the block state transition of the block is `onchain Merkle root -> new Merkle root` and the new Merkle root is stored in the contract.

Both methods can actually work on the same Account Merkle tree we have now without any changes to the Exchange contract! We just need to make sure that an order forces where it's trading history is stored (otherwise it could be settled twice) which can easily be done by making the orders incompatible between the circuits. 

The same method could be used for future circuits that need extra data to work.

**Comment by dong77** [comment]
please refer to #289
