### ISSUE TITLE
[Protocol3.1] general discussion on a cross-chain architecture

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#312]
migrated to https://github.com/Loopring/lightcone2/issues/683

**Comment by dong77** [comment]
@Brechtpd @letsgoustc @kongliangzhong 
Let's talk about this in our next weekly meeting.

**Comment by Brechtpd** [comment]
Some interesting links:
- Barry's talk about cross chain/shard rollup: https://youtu.be/RW7K3JQOZOg?t=10712
- Vitalik's data availability on bitcoin cash proposal: https://ethresear.ch/t/bitcoin-cash-a-short-term-data-availability-layer-for-ethereum/5735
  - Interesting for a number of reasons, but especially for the cross chain POW verifying (like btcrelay), we'll probably need something similar for all the chains we want to support. Otherwise we need less secure things like oracles I think.

We also only need to publish the DA data on a single chain. This is nice because the throughput we can achieve across all chains is only limited by the best chain for this.

**Comment by Brechtpd** [comment]
## **WIP! This post will be updated continuously for a while**

Let's start with the most difficult part: the need for some kind of cross-chain communication.

## Communication between chains

Without some form of communications between chains we cannot ensure that both chains have the same state. If they don't have the same state we cannot do cross-chain trades because the chains may divert at any point (e.g. the balances of an account may differ on the different chains). The state transitions can be valid on both chains, but they NEED to be the same transitions on the same states.

So how do we do this? Unfortunately this is hard and even existing projects that aim to tackle this problem don't seem to have code running on Ethereum mainnet:
- [Peggy](https://github.com/cosmos/peggy) from Cosmos.
- [Polkadot bridges](https://wiki.polkadot.network/en/latest/polkadot/learn/bridges/)

We do have something existing solutions for BTC (and forks):
- http://btcrelay.org/
- https://github.com/summa-tx/bitcoin-spv/

The main idea is that we check the POW using the block headers of the other chain. We can than use a Merkle proof on the active chain to show that some transaction or event has occurred on a different chain. If we want to allow cross-chain trades between Ethereum and Cosmos for example we need to validate the Ethereum block headers on Cosmos and we need to validate the Cosmos block headers on Ethereum.

So a pretty good solution exists for BTC. But this doesn't exist yet for Ethereum because it's MUCH more difficult to validate the POW of Ethereum headers compared to the POW of Bitcoin. Instead of a simple sha256 to hash the header we need to use (Ethash)[https://github.com/ethereum/wiki/wiki/Ethash] for Ethereum headers.

### Ethash

For Bitcoin we can everything on-chain because it's cheap (sha256 is a cheap instruction). Everything about Ethash is expensive:
- the main hash function is sha3-512 (expensive on-chain and expensive in a circuit)
- Expensive to generate the 16MB cache
- Expensive to generate the necessary dataset part
- ...

It's so expensive we can't do it on-chain. Luckily we have ZPS, but even then we can't really do everything we need to do in a circuit with a reasonable cost. I think even validating a single Ethereum header in a circuit would use more constraints than we can use in a single block!

But I think it can be done using fraud proofs. We don't have any data-availability of course because all the data is available from Ethereum itself, so we can split Ethash up in multiple parts for which a fraud proof CAN be provided for a reasonable cost. Quick idea:
- Multiple headers are validated in a single block. These headers are added to Merkle tree and only the Merkle root is stored on-chain. A Merkle proof can than be to get the header of a single block.
- A Merkle tree is also used to store which data was used for the dataset part. The root is added to Merkle tree and if the wrong data was used a fraud proof can be submitted (there are 64 data set parts, so this lowers the cost by 1/64).
- Other parts (cache generation) can be split up as well
- ...

### Cosmos/Polkadot headers

The above is just for Ethereum on another chain. For every other chain we need to do the same on all other chains!

### No real POW validation, use consortium that publishes the headers

To lower the cost (and to actually make this possible without ZKPs) we could also just check some signatures from a consortium (like some projects are doing to tackle this problem). But this would of course bring about all the bad things with these kind of things, with ZKPs I feel we can do better.

### Conclusion

This is by far the hardest thing we need for a good cross-chain exchange. Ideally we can use something other projects are already building.

## Protocol

Here we assume that we have some way to check data on other chains. More specifically, we assume here we can check that an event has been emitted on another chain (which is possible using a Merkle proof and a valid Ethereum header). Some other mechanism (e.g. reading state directly from a contract) would also work (which can be proven similarly as the event).

### Accounts

The most flexible way would allow the creation of accounts on any chain. A user only needs to create an account on a single chain and can then trade tokens on any other chain. If he wants to withdraw the tokens from a different chain where he created the account on he needs to unlock his account first.

#### Account creation

We can allow the creation of an account on any chain in 2 ways:
1. We split the account tree in multiple fixed parts. Every chain gets a fixed range in which it can create an account. This is simple, but it can be hard to predict how many accounts a chain needs so this can be wasteful.
2. We use an account range registration contract on Ethereum. This contract manages which chain can use which account ranges. Initially no accounts can be created on any chain. The exchange owner can than e.g. reserve accountID range 0 - 999 for Ethereum and accountID range 1000 - 1999 for Cosmos. Afterwards we reserve an additional accountID range of 2000 - 2999 for Ethereum. Each time a range is reserved an account is logged. Other chains can use a Merkle proof for that Event to proof that the account range was reserved for some chain.
3. We could also simply force everyone to create their account on Ethereum. Option 2. above is more flexible.

Option 2 seems to the best solution.

#### Account unlocking

So a user has created an account on Ethereum, bought some NEO and now wants to withdraw the NEO to his NEO wallet. The exchange does not yet know what the NEO address is of that user on NEO, so he cannot interact with the NEO part of the exchange. First he needs to unlock his account there. Not that this may happen even after the exchange has gone in withdrawal mode, so ideally we have a solution that works without the help of an operator.

A user can proof that he is the owner of an account on any chain by signing some message with his EdDSA keypair. Together with a Merkle proof that there is indeed an account at accountID X that has this EdDSA public key for some Merkle root. When this validation passes the user is now the owner of that accountID X on the different chain and thus has a valid owner address that is used to interact with the contract but also to withdraw his tokens to.

A minor security issue with this method is that we need to allow multiple Merkle roots to be used to check the Merkle proof against. We can't just use the latest Merkle root because the operator will be changing this Merkle root every time he commits a block. We also don't want to allow any Merkle root to be used because the user may have changed his EdDSA key because of security concern. A practical solution for this is to only allow a Merkle root to be used that is finalized (important, a malicious operator can change the EdDSA key temporarily in an invalid block) either ~1 hour or the latest finalized Merkle root (needed for when an exchange is inactive for a long time).

### Account data stored on-chain

We currently store the EdDSA key on-chain. Because EdDSA public key can be updated on multiple chains the on-chain data may be incorrect. (the data in the Merkle tree is of course the same for all chains automatically). This should be fine, this data is on-chain mainly for easier public API (e.g. depositTo, which will update the the key in the Merkle tree to the values stored on-chain, so if this can happen the deposit function with the public key data as input should be used).

### Tokens

For tokens we can use the same kind of methods described for accounts:
1. Each chain gets a fixed range
2. A token registration contract on Ethereum that logs an Event for each token (ranges seem unnecessary) that can be used on different chains.

Option 2 here would be the best. Option 2 is also great for something I'll call mirror tokens from here on out which adds flexibility and solves some problems.

#### Mirror tokens

The idea here is that tokens from other chains would always have an equivalent ERC20 token on Ethereum. Either there is an existing mirror token like this already (like tBTC or WBTC), or a new ERC20 token is created. This allows a token from a different chain to be used just like any other token on Ethereum.

Example: Let's say a user buys NEO without having a need to actually use it on NEO itself. With the mirror token he would now be able to withdraw the mNEO and store it on his hardware wallet or even use it in his favority open finance dapp. Of course, if Loopring exchanges allow this there needs to be some way to get the actual NEO token without the need of an operator. The cross-chain infrastructure needs to be decentralized and guaranteed up and running for this to be possible. A burn/mint contract to swap between mNEO and NEO is not hard to do (e.g. just check for a Burn Event to mint tokens on the other chain).

This also solves the problem of the staking. All staking rewards would be paid in mERC20 tokens. Users can than get the actual token on the other chain be e.g. depositing the mERC20 token on a Loopring exchange and withdrawing it on the other chain. But like described above, a manual method for exchanging mERC20 tokens with the actual token would also need to be available for this to be safe.

### Cross-link and finalization

At some points in time the exchange will have to a cross-link. This means that for some blockIdx the Merkle root for all chains need to be the same. This makes sure the exchange state on all chains don't diverge from each other. Only after a cross-link can a block be completely finalized. To keep our current definition of finalized (the block is verified and all previous blocks are verified as well), we will call this cross-finalized. Only when a block is cross-finalized is it irreversible.

A block can be made cross-finalized:
- The block needs to be finalized on the main chain (Ethereum)
- The block just needs to be committed on all other chains

To make things simpler, we only allow blocks to be manually reverted on the main chain (Ethereum). Blocks on all other chain can only be reverted by using a cross-link on a block that is already finalized on the main chain, and which will fail because the block on the chain has a different state. This is to make sure a chain cannot modify the blocks while a cross-link was already performed for some chains.

If a revert happens not on the main chain the revert event can be used as proof on the main chain to burn part of the exchange stake. This way we limit the exchange stake to the main chain, no need for any staking on a different chain.

The cross-link time is important for finalization (so quicker/more frequent is better, finalization is needed for withdrawals) but it will have a cost. Depending on the cost we can decide on the frequency.

#### Proof verification

We do not need to verify a block on all chains, we only need to verify the block on the main (Ethereum) chain.

We can't just use the main chain as the truth because the main chain does not have all on-chain data (e.g. how much was deposited on a certain chain). This is checked on-chain on a single chain, so the main chain cannot check it and so cannot verify it. But this check is done when the block is committed, so if the block can be successfully committed on that chain than that's enough. The actual state transitions in the Merkle tree verified with the SNARK proof only needs to be done once so only doing it on the main chain is enough.

### On-chain data-availability

Data availability can be done on any chain (even on a different chain/block, though that makes things harder to keep track of). Easiest would be to do the on-chain data availability on a single chain (e.g. where it is cheapest) or just on all chains (which would be the most secure).

### Withdrawal mode

We may go in withdrawal mode at different times (or maybe not at all) on different chains and/or on different cross-finalized blocks.

After withdrawal mode starts on a chain these conditions need to be proven using cross-links on a chain
  - The main chain is in withdrawal mode
  - There is a valid cross-link at blockIdx (the correct block that needs to be used for withdrawal mode)
  - The is an invalid cross-link at blockIdx + 1. This not only proves that withdrawal mode uses the latest completely valid block, it also makes sure the same block is used on ALL chains for withdrawal mode. This is important, otherwise withdrawals are possible on different states on different chains.

If we support mirror tokens than we cannot allow withdrawing like that in withdrawal mode. Only native tokens to the chain can be withdrawn (otherwise we'd have to keep track of what the user has withdrawn on a chain, if not a user could withdraw the same tokens on multiple chains).

### Shutdown

The owner can start shutdown mode on all/some chains independently. If not done correctly we use the cross-link to revert blocks where necessary.

Not much to gain from doing it only on a single chain:
  - Only existing deposits can be done, afterwards any withdrawal.
  - Other block types can still be committed on other chains, but these blocks cannot be cross-finalized so will need to be reverted.
  - An exchange can only be shutdown mode for a limited time. Eventually the exchange will need to be put in shutdown on the other chains or we go into withdrawal mode.

Once completely shutdown the block needs to be cross-finalized on the main chain. The exchange stake can then be withdrawn on the main chain (there is not staking on different stakes, so nothing needs to become withdrawable on non-main chains).

### Maintenance mode

The owner can start/stop maintenance mode on all/some chains independently. I currently see no need for this to be consistent over chains.

### On-chain requests

On-chain requests would work pretty much unmodified. We will need to use a chainID because the on-chain data that is validated on-chain is only available on a single chain. If the `chainID == currentChainID` we check if the on-chain data matches the input of the block, on chains the on-chain requests weren't done we don't check that input and just allow the block to be committed.

We can only do deposits/on-chain withdrawal requests for a single chain at a time. numDeposits/numOnchainWithdrawals are only updated for the chain the requests were processed.
The block fee will be withdrawable on the chain of the on-chain requests once cross-finalized.

### Approved withdrawal data

The approved withdrawal data can contain withdrawals for tokens from different chains.
- We can simply skip/disable the withdrawal if the tokenID is from a different chain.
- We can also simply force all withdrawals to be for a certain chain to optimize for this (this data needs to be stored on-chain, so if all withdrawals are from a different chain we don't need to store any data).

With mirror tokens the user would have to additionally provide on which chain he wants to withdraw the tokens (which would allow him to withdraw either the real tokens or mirrored tokens).

### Protocol fee values

The values used in a trade block are checked on Ethereum but not on other chains.

### User staking

Easy to do with mirror tokens (all fees get withdrawn to the staking contract even if they are not native tokens). Otherwise this is more difficult, though some basic version of that is probably needed to correctly calculate how much each user needs to receive if those calculations are only done on Ethereum.

### Admin commands

Admin commands not specifically listed elsewhere need to be done on all chains independently. This makes sense: on-chain fees need to use a different currency, the operator address will be different,...

**Comment by dong77** [comment]
## regarding "Communication between chains"

A couple of months ago, I had this feeling that cross-chain is finally possible based on our current protocol design. We can use the off-chain Merkle tree as the bridge between multiple chains. I don't like other approaches I know because I feel they are cumbersome. 

For each chain's perspective, as long as the Merkle tree is valid, the entire state is considered to be correct. For example, assume we support Chain A and B. When a user deposit token A1 which is native on chain A, the protocol contract on chain A will verify the transfer of token in the original user deposit request, and do all the work we are doing right now. 

On chain B, the smart protocol contract will skip checking the origin user request (because there is none) and only verifies using SNARK that the new state root is correct.

We want to enforce the two virtual blockchains on all chains to have the same state roots eventually after N blocks. We can use fraud proofs to allow anyone to challenge the DEX. For example, assuming the current block index is 10000 on chain A and 10010 on chain B, if someone can get a signed state root with index 910 on chain B (denoted as R_b910), he/she can submit R_b910 to chain A to punish the DEx if R_b910 != R_a910. Here we give 100 as the N parameter.
