### ISSUE TITLE
[Protocol3] Allow DEX operators to reject account creation requests and send back tokens

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#317]
Our current design guarantees that all deposit requests will be handled and corresponding offchain accounts will be created. We should allow DEX operators to reject certain account creation requests, i.e, based on an off-chain address whitelist.

Balances associated with rejected deposits should be returned to users automatically in the same block, this requires some work. We should also consider how to prevent a Sybil account-creation attack as sending-back tokens will cost gas.

**Comment by dong77** [comment]
@Brechtpd this may imply more work than expected.

**Comment by Brechtpd** [comment]
Only ETH will need to be sent back immediately (which we already do when the user pays too much fee), tokens are transferred inside the contract in `deposit` so the function will not get there when doing the check earlier.

It's the depositor that pays all the gas for on-chain requests so I don't think any attack is possible.

**Comment by dong77** [comment]
When a user is trying to create an account by depositing 10 LRC, those LRC will also be transferred to the DEX contract. Later when the operator decides to reject this request, those 10 LRC should be returned to the user in the corresponding deposit block.  Right?

**Comment by Brechtpd** [comment]
Ah I think I understand the confusion. So my idea was that the signature check would still be checked on-chain, not off-chain at a later time. Something like this:
- A user wants to create an account and lets the DEX know
- The DEX signs something like (exchangeID, userAddress) and gives the user the signature
- The user can now create create an account with the given signature by passing it to e.g. `createOrUpdateAccount`.
- On-chain we check that the signature was created by the DEX, otherwise we reject the request immediately.

Now that I think about this, an even simpler way to do this is to only allow the DEX to create accounts. A user can then check if the owner of the account is his address (using `getAccount`) and can then start using it. We'd have to create a new function like `createAccountFor` or something like this

If we make the interface something like `isWhitelisted(address accountCreator, address accountOwner, bytes data)` the DEX can implement their own solution (only allow a certain accountCreator (== msg.sender) to create accounts, using whitelisted addresses stored onchain, by sending the signature in `data`, ...).

**Comment by dong77** [comment]
I also removed this issue from beta3, FYI.

**Comment by dong77** [comment]
If we can safely assume there are enough slots for accounts, maybe it's quite OK for anyone to be able to create any number of accounts with a fee -- when there are 50% slots used, the operator can increase the account creation fee by a factor of two or there.  The fee should be set so that no one will not likely to spend that much money to create too many accounts as a Sybil attack.

The operator does not impose any restriction onchain and will only maintain an off-chine list of accounts that they will match orders and perform ring-settlement for.  Of course, this is where we are now.

**Comment by dong77** [comment]
I actually like your idea of using a DEX signature as a parameter in create account, we can make this a feature that can be disabled. 

The signature can be created by the DEX operator’s private keg against the address that is trying to register an account. The if can still be determined later.

**Comment by dong77** [comment]
I’ll try to create a PR for this.

**Comment by dong77** [comment]
As implemented in #329, each DEX now has a fully customizable `addressWhitelist` address to point to an `IAddressWhitelist` implementation which decides whether an account creation will be handled.
