### ISSUE TITLE
Charge the on-chain deposit/withdrawal fees using the token instead of Ether

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#489]
The main idea is to enable people to pay the deposit and withdraw fees using the token being deposited/withdrawn because that's probably what they have the most, not ether.

We currently charge Ether **beforehand** because we don't know if they really have enough token to pay for the fee before we process the request. 

What we can do can be:

1. The user pays Ether as the request fee
2. After we process the request,  if the user's token being deposited or withdrawn is sufficient to pay the fee, deduct the fee from the token amount and return Ether to the user; otherwise, keep the Ether fee.
3. If the user prefers to pay in tokens, a flag must be set to True in the request.

The fee percentage for each token is part of the smart contract and can be configured by the owner. If the owner prefers charge Ether as the fee, he will set the token fee amount higher.

**Comment by Brechtpd** [comment]
The main reasons we use ETH for the fee:
- It's cheaper: ~2000 gas for an ETH transfer vs ~15000-2000 for an ERC-20 transfer
- Easy to calculate and pay the block fee (or fine him if the operator took to long to process the requests): The operator can withdraw the fees when the block that processed the on-chain requests is finalized. Only having a single currency makes this fast and efficient. If there is the possibility for multiple tokens this is pretty much impossible for even a moderate amount of processed requests (either complex/expensive to batch the payments and/or VERY expensive to do all necessary token transfers).
- The user has ETH anyway, otherwise he wouldn't be able to call the smart contract

This would be hard to implement, would make the on-chain part more expensive and I don't think we really need it, especially with the meta transaction method for deposits in #318 . For deposits the user can use meta transaction so he doesn't need to pay in ETH (depends on how the fee payment can be done efficiently here, not sure yet) and for withdrawing an off-chain withdrawal request or fast-withdrawal request can be used which allows the user to pay the fee in any token already.

We could also immediately send a % from the deposit amount to the exchange owner (this could be on top of the ETH fee we charge now to the operator). Both fees can be non-zero. This way we can support more centralized exchanges (they would only charge a % from the deposit and no ETH fee because the operator is the same entity as the exchange owner anyway) and decentralize exchanges (don't charge % from the deposit and only a ETH fee to the operator that actually processes the request).

But... isn't there a big chance of the deposit fee being 0 anyway for all exchanges? I don't think any exchange charges a deposit fee, they do fees on withdrawals (which makes sense, you have a choice to deposit and want to look as attractive a place to trade as possible but you have to pay the fee if you want to get your money out). I would find it very strange if I would want to start using an exchange and immediately lose a % of my deposit. I would be very hesitant to start using an exchange like this to be honest. It would something an exchange could do if it wants I guess, but this doesn't seem to be a very attractive feature.

**Comment by dong77** [comment]
After a second thought, I agree with you. The current deposit/withdrawal fee model should be fine. Closing this issue.
