### ISSUE TITLE
[Protocol3] Accounts may be created after shutdown, allowing shutdown to be extended.

### ISSUE THREAD

**Issue by RobertMCForster** [Loopring/protocols#493]
Again, sorry about the formatting...not sure if I have permission to add labels.

When [creating an account on ExchangeAccounts.sol](https://github.com/Loopring/protocols/blob/b6992c2618f513ffacdd51d04145c999e6323ca3/packages/loopring_v3/contracts/impl/libexchange/ExchangeAccounts.sol#L90), there is no protection requiring the contract not be shutdown.

This shouldn't be allowed in the first place but it also allows anyone (with some money) to extend the shutdown up to just about 6 months because of [this line in ExchangeMode.sol](https://github.com/Loopring/protocols/blob/b6992c2618f513ffacdd51d04145c999e6323ca3/packages/loopring_v3/contracts/impl/libexchange/ExchangeMode.sol#L63).

I'd recommend just adding a require in account creation to make sure the contract isn't in shutdown. If it's necessary to create accounts after shutdown for some reason, maybe a variable can be initialized on shutdown that saves the current number of accounts and limits shutdown time to that.

**Comment by Brechtpd** [comment]
Hi @RobertMCForster, thank you for reviewing our code and this report!

You're correct that it should NOT be possible to create an account in shutdown and I don't think it can be done. At least I hope so. :)

An account can only be created through [Exchange.updateAccountAndDepositInternal()](https://github.com/Loopring/protocols/blob/05d710d7ea775a058102a26c74bfc9a868aa8694/packages/loopring_v3/contracts/impl/ExchangeV3.sol#L838) (this internal function is called by the public functions Exchange.createOrUpdateAccount() and Exchange.updateAccountAndDeposit()). 

Exchange.updateAccountAndDepositInternal() always calls ExchangeDeposits.depositTo() which does have a require with a call to [ExchangeMode.areUserRequestsEnabled()](https://github.com/Loopring/protocols/blob/05d710d7ea775a058102a26c74bfc9a868aa8694/packages/loopring_v3/contracts/impl/libexchange/ExchangeDeposits.sol#L79) which [checks if the exchange is in shutdown or not](https://github.com/Loopring/protocols/blob/05d710d7ea775a058102a26c74bfc9a868aa8694/packages/loopring_v3/contracts/impl/libexchange/ExchangeMode.sol#L113).

So while it passes through the account creation without problem, the transaction will fail in depositTo(). depositTo() is always called so that the Merkle tree state is kept up to date with the on-chain state (account creation and depositing uses the same circuit for updating the Merkle tree, which could be confusing).

Please let me know if you agree or not! Thanks!

**Comment by RobertMCForster** [comment]
Ahhh beautiful, overlooked that one. Thanks for the response!
