### ISSUE TITLE
[Protocol3] Exchange stakes can all be wiped in case of a major network jam

### ISSUE THREAD

**Issue by RobertMCForster** [Loopring/protocols#494]
This is likely out-of-scope for the bug bounty, but I thought I'd comment anyway cause I have a possible suggestion.

If anyone manages to completely jam the Ethereum network with arbitrary transactions for a full day, every exchange could have their stakes immediately wiped.

I'm sure you guys have thought about this, but I was thinking it may be best if exchange stakes were wiped a % at a time over the course of a few days. For example, maybe 33% of stake may be wiped each day for 3 days.

**Comment by Brechtpd** [comment]
You're certainly correct that an exchange owner/operator isn't completely without risk even when acting in good faith. Though jamming the Ethereum network for a complete day seems unlikely because an attacker would have to outbid the exchange owner/operator for ALL transactions in that day, while the exchange owner/operator only need a couple of transaction in a day to make sure the exchange doesn't go into withdrawal mode so the exchange stake doesn't get burned. Because they have a lot to lose, it makes sense to outbid everyone for those couple of transactions even if the cost is very large.

Other problems could of course be that the Ethereum blockchain gets stuck for a while, Ethereum miners don't want to include the transactions in a block for some reason, etc... It is no doubt important that these time constants are chosen wisely, but it will never be 100% risk free.

Gradual burning of the exchange stake is an interesting idea to mitigate the external risks some more. But it could make certain things harder to implement and should not really be possible (assuming 'normal' behaviour of Ethereum). I'll have to think about it some more!

Thanks for the suggestion!

**Comment by dong77** [comment]
We will handle this by making the protocol parameters more reasonable (or more 'relaxed').
