### ISSUE TITLE
[Loopring3] Perform Trusted Setup

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#610]
https://github.com/Loopring/trusted_setup

**Comment by Brechtpd** [comment]
If we want to start phase 2 before the middle of November we shouldn't wait much longer before doing the work that's needed before we can kick of phase 2. Some of the steps need lots of CPU/memory/storage that make it pretty much impossible to do everything on a normal PC in the time schedule we currently have, so I'll be doing some of the steps on AWS.

Complete instructions on how to do everything can be found here:
- https://github.com/Brechtpd/trusted_setup/tree/mpc#instructions-for-the-coordinator

Below are the steps I would take.

#### 1. 'Fork' from phase 1

After Daniel's contribution (ready ~1 day from when this post was created) I would do the random beacon step so we'll have to decide on a bitcoin block. We should announce on the Loopring twitter account and here on Github which bitcoin block we will use for that. Once the bitcoin block is mined I can start the random beacon contribution with the block hash and extract the necessary data for phase 2. These steps will take a few of days.

#### 2. Setup the circuits for phase 2

We can now setup the circuits with the data of phase 1. This also takes a very long time to do on a normal computer.

I would propose we'd do the trusted setup for the following circuits (all _with_ on-chain data-availability):
- Ring settlement: 2**n, n in [0, 12] (up to max capacity/block)
- Deposits: 2**n, n in [0, 8]
- on-chain withdrawal: 2**n, n in [0, 8]
- off-chain withdrawal: 2**n, n in [0, 8]
- order cancellation: 2**n, n in [0, 8]
- internal transfers: 2**n, n in [0, 8]

Only for the ring settlement blocks would I go to the max capacity we can/block. Otherwise the contribution file will be too big, see below.
To make the prover more optimal the actual number will differ a bit from the nice power-of-2 numbers presented here (the prover is more optimal when _the number of constraints_ in a circuit is slightly below a power-of-2).
Very roughly the following is true:
- A request is ~70,000 constraints
- 1M constraints needs ~256MB storage in the contribution file (the file that needs to be downloaded and uploaded by all participants)
- 1M constraints needs ~2 minutes of CPU time on a 4-core CPU.

With the the circuits above in the trusted setup we'd have roughly 627M constraints in total so:
- a contribution file of ~150GB
- ~20 hours of CPU time for the computation

Setting these circuits up before we can start the actual trusted setup is also very computation heavy and will certainly take a couple of days (even on AWS).

**Comment by dong77** [comment]
I suggest to further restrict the permutation to the following:

```
Ring settlement: 2**n, n in [6, 12] (up to max capacity/block)
Deposits: 2**n, n in [5, 8]
on-chain withdrawal: 2**n, n in [5, 8]
off-chain withdrawal: 2**n, n in [5, 8]
order cancellation: 2**n, n in [5, 8]
internal transfers: 2**n, n in [5, 8]
```

**Comment by Brechtpd** [comment]
> Will this reduce the time of the setup computation?

Removing the small permutations doesn't really impact the total computation/storage cost because they have very few constraints, so I kept them in because they can come in handy (testing etc...) and don't really cost anything significantly.

Removing the very big blocks drastically reduce every cost because they contain A LOT of constraints, so the `Ring settlement: 2**n, n in [6, 10]` limitation to 2**10 would be much faster.

**Comment by dong77** [comment]
OK, let's use 10 as the cap for settlement then.

**Comment by Brechtpd** [comment]
The circuits I am planning on doing the trusted setup for:
Ring settlement: 1, 2, 4, 8, 14, 29, 61, 123, 249, 499, 999 (may still change for final code)
Deposit: 1, 2, 4, 8, **15, 31**, 64, 128, 256
On-chain withdrawal: 1, 2, 4, 8, 16, 32, 64, 128, 256
Off-chain withdrawal: 1, 2, 4, 8, 16, 32, 64, 128, 256
Order cancellation: 1, 2, 4, 8, 16, 32, 64, 128, 256
Internal transfer: 1, 2, 4, 8, 28, 58, 120, 243

This is so that the total number of constraints in the circuit is close to a power-of-2 to optimize the proving times. I also just do 1, 2, 4, 8 requests/block for every request type because for a low number of requests it's impossible to get close to a power-of-2 number of constraints.  

When the circuit was already quite close to this optimal I stuck with the nice power-of-2 number of requests/block. Ring settlement: and internal transfers are arguably the most important circuits because they are completely off-chain so they scale very well, so I made sure we're very close to optimal for those.

@hosschao

**Comment by dong77** [comment]
@hosschao our relayer engineers need to learn those numbers once they are finalized

**Comment by dong77** [comment]
https://loopring.org/#/ceremony can be used to publish the status.

**Comment by dong77** [comment]
As all data/information is saved in https://github.com/Loopring/trusted_setup. I think we can safely close this issue as well. @Brechtpd

**Comment by Brechtpd** [comment]
That makes sense. Closing this.
