### ISSUE TITLE
[Protocol3] One question on OrderID & TradingHistoryID

### ISSUE THREAD

**Issue by yueawang** [Loopring/protocols#622]
According to the design doc [TradingHistory](https://github.com/Loopring/protocols/blob/master/packages/loopring_v3/DESIGN.md#trading-history).
It turns out OrderID must be greater equal than the TradingHistoryID.
I just wonder why we have such limitations? It seems OrderID can not be reused in a loop manner, because once OrderID goes back to 0, it less than the TradingHistoryID.
Now we have 2**20 order id slots, which means they run out in ~180 days if 1 block contains 1 settled order, because of `(2**20)*15/3600/24 ~= 182`.
Is that a problem?? Should we extend the OrderID to 24bit to make that overflow infeasible?
Thanks!

**Comment by Brechtpd** [comment]
The `order.orderID > tradeHistory.orderID` check is against the `orderID` stored in the leaf. So in a new account for every token there are `2**14` trading history leafs that all have `orderID == 0` and `filled == 0` stored in the leaf, so in the beginning any `order.orderID` can be used because `0 >= tradeHistory.orderID`. After that slots are reused: e.g. `orderID == 2**14 + 5` will reuse trading history leaf slot 5.

But yes, once you're at `orderID == 2**20 - 1` you cannot reuse any slots anymore (and slots could have been reused `2**6` times) with the current method. The reason the orderID is limited is for 2 reasons:
- The complete orderID is stored in the calldata. So the larger the max value the more bytes we need store in the calldata (which lowers the throughput and increases the cost)
- Because of that, users can choose any orderID in their orders (no fixed increments of orderIDs necessary, see below)

Another way this could have been done is to only put `2**14` bits in the calldata + an extra flag that the leaf was overwritten. But this doesn't save a lot of calldata bytes (which will be mostly cheap 0 bytes for most users) and is a bit more complex and less flexible (because the orderID would always need to increase exactly `2**14` for every leaf, and never a multiple of that). But this would also be a good solution.

The costs of things changed with Poseidon + lower calldata costs with Istanbul, but I think the current limits are more than large enough so I didn't want to do any changes:
- There are `2**20` ID's _for each token_.
- `orderID`s for orders that don't get filled can also be reused (if an order doesn't get filled it's like the order never existed for the protocol)! So you would need  `2**20` unique orders _for a specific tokenS_ that actually all get filled.
- If someone would still be able to fill the complete trading history tree (which will no doubt be pro traders) they can quickly and easily transfer their funds with internal transfers to a new account to continue trading with a new trading history tree. 

Because of these reasons I would actually say that the current limits are _too large_.

**Comment by dong77** [comment]
2**20 is about I million orders per account/token. This seems to be too small for professional market makers, but I believe they can easily get around this limitation by creating more accounts.

**Comment by dong77** [comment]
I agree.
