### ISSUE TITLE
[Protocol3]  Can we require the nonce of Account monotone increasing without limit the step size

### ISSUE THREAD

**Issue by lydy** [Loopring/protocols#635]
> #### Only Allow Off-chain Requests to be Used Once
> The **nonce** of the account is increased by 1 for these operations. The expected nonce is stored in the off-chain request which is signed by the account owner.

https://github.com/Loopring/protocols/blob/master/packages/loopring_v3/DESIGN.md#only-allow-off-chain-requests-to-be-used-once

The step of nonce is 1, can we require it monotone increasing without limit the step size.

**Comment by Brechtpd** [comment]
- It's cheaper if the nonce it always incremented by 1. Because the nonce is stored in the Merkle tree we need to be able to reconstruct the value correctly using the on-chain data-availability data. If the nonce is always increase by once this is simple and we don't even have to put anything on-chain: If we e.g. see an off-chain withdrawal of a user we know we have to increase the nonce of that user by 1, always. If the nonce isn't always increased by 1 we would have to put extra data on-chain so we know what the new nonce value is after the off-chain withdrawal which increases gas costs.
- Sometimes a strict ordering of requests is wanted by users. For example, let's say a user does an internal transfer of 1 ETH to a new account (request.nonce == 1) and does an off-chain withdrawal request of that 1ETH (request.nonce == 2). The user does NOT want the off-chain withdrawal request to be processed before the internal transfer request because the user may need to pay a fee for the off-chain withdrawal request. And without doing the internal transfer nothing is withdrawn so the user pays a fee for nothing! And because the nonce of the user would now be 2, his first request can't even be used any more!

The user can of course always 'overwrite' requests by creating new requests with the same nonce as long as they haven't been included yet in a block. So for example, the user can create an off-chain withdrawal request with `fee == 0.001ETH` and `nonce == 5`. If the operator doesn't want to do the request for such a low fee the user can make a new request, now with `fee == 0.01ETH` and `nonce == 5`. There are now 2 requests with `nonce == 5` but only one of them can be included in a block by the operator!

**Comment by hosschao** [comment]
@Brechtpd The requirement is that: if user submit off-chain request(like off-chain withdraw1) which nonce is 1, and some other off-chain requests (nonce is 11 now). After that, if we need cancel withdraw1 in some cases(maybe we can support canceling off-chain request in future), all following off-chain requests should be cancelled(bad nonce).
I think only monotone increasing is good enough. Circuit could check whether nonce is increasing and reject request which nonce is less than current seen max nonce. The 2 advantages you mentioned above also maintained.

**Comment by Brechtpd** [comment]
> The requirement is that: if user submit off-chain request(like off-chain withdraw1) which nonce is 1, and some other off-chain requests (nonce is 11 now). After that, if we need cancel withdraw1 in some cases(maybe we can support canceling off-chain request in future), all following off-chain requests should be cancelled(bad nonce).

Cancelling an off-chain request is easy: just let the user sign some dummy off-chain request with the same nonce of the request the user wants to cancel.  So if the user wants to cancel an off-chain withdrawal with `request.nonce = 1` without invalidating all requests that follow it, the user can sign e.g. an internal transfer request (because these are the cheapest off-chain requests) with `request.nonce = 1` that doesn't actually transfer anything. This request will still need to pay a fee though because it still needs to be included in a block like a normal request. But this would only be needed if there are requests that follow it that the user wants to keep (without any resigning of requests). If there are no requests that follow it (or all requests that follow it should also be cancelled) the exchange can just do a 'soft cancel' and just throw away the requests (the user needs to trust the exchange in this case of course).

**Comment by lydy** [comment]
We can do it by re-signature a dummy request with the same nonce, but the user needs to pay a small fee as you mentioned.
If we allow the nonce increasing without the step size,  the Relayer can just drop this withdrawal with `request.nonce=1` when the user wants to cancel. The Relayer can continue to do the next withdrawal with `request.nonce=2`. 
I think it's more smoothly and the user needn't pay any fee.

**Comment by dong77** [comment]
I understand that relayer engineers want to have some flexibility so scalability can be achieved easier. In general, I lean towards relaxing the restriction a bit, but before a decision can be made, we need to evaluate the throughput impact, after all, we will have to store the nonce value on-chain for each offchain request now after such a modification.

If we don't consider the save-nonce-on-chain side effect, I guess a "strictly +1" approach and a "+any" approach are equivalent in terms of achieving the same user behaviors or interactions. I welcome counter-examples :) @Brechtpd

**Comment by Brechtpd** [comment]
> I guess a "strictly +1" approach and a "+any" approach are equivalent in terms of achieving the same user behaviors or interactions. I welcome counter-examples

Point 2 of my initial reply is a counter example. The operator doesn't have to do the user's request in a specific order which means the operator can skip over any number of requests which can produce unwanted effects for the user. Though this is not the biggest problem with our current functionality.

The way the nonces currently work is the same as Ethereum which seems to work alright. :)

**Comment by dong77** [comment]
I see the point.  The other thing I agree to is that 'nonce' is really a well-received concept in the blockchain community.
