### ISSUE TITLE
[Protocol3]  Make LRC/ETH protocol-wise configuration possible for dynamic calculation

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#695]
```solidity
        address _downtimeCostCalculator,
        uint    _exchangeCreationCostLRC,
        uint    _maxWithdrawalFee,
        uint    _tokenRegistrationFeeLRCBase,
        uint    _tokenRegistrationFeeLRCDelta,
        uint    _minExchangeStakeWithDataAvailability,
        uint    _minExchangeStakeWithoutDataAvailability,
        uint    _revertFineLRC,
        uint    _withdrawalFineLRC
```

In LoopringV3, we have the above configuration whose values really depends on the price of LRC and Ether. Maybe we can create something like the following that utilize a price oracle to give dynamic values.

```solidity

interface LoopringConfiguration {
        function   exchangeCreationCostLRC() public view returns(uint):
         ...
}

contract FixedLoopringConfiguration {
        constructor(address priceOracle) public {...}

        function   exchangeCreationCostLRC() public view returns(uint) {
             return 1000 ether;
        }
         ...
}
contract OracleBasedLoopringConfiguration {
        function   exchangeCreationCostLRC() public view returns(uint) {
             return 1000USD/Oracle(priceOracle).getLRCPriceUsd();
        }
         ...
}

```

**Comment by Brechtpd** [comment]
That's a good idea. But I think it would be best to implement this completely using the owner contract of LoopringV3 because there's no real need to do it in the LoopringV3 itself (the owner contract can just call `updateSettings` using any logic it wants). I don't think it would be a good idea to use the real-time value of these prices anyway when an oracle is used because prices can fluctuate widely which can cause a lot of issues if they are applied directly (like making the exchange unusable). So some kind of mechanism that allows these costs to be updated with some delay (so exchanges have enough time to prepare) completely transparent would be useful.
