### ISSUE TITLE
[Loopring3] Price feed / oracle considerations

### ISSUE THREAD

**Issue by mfinestone** [Loopring/protocols#696]
A general discussion around 1) in which ways and for what purposes Loopring 3.0 needs to consume price feed information, and 2) how it can make itself conducive to be used as input for these oracles.

## Consuming price feed ##

- For triggering Stop Limit orders, and other advanced order types
- For LRC staking by the DEX owner; dynamic stake amount as opposed to fixed
- For margin/leverage, derivatives, etc.

## Input for price feed ##

- DEX browser, unpacking the trade data from Loopring trades

**Comment by dong77** [comment]
It's possible to use a price oracle offchain and onchain, for example:
- onchain: we can use price oracle to [dynamically calculate](https://github.com/Loopring/protocols/issues/695) how many LRC are required to create a new DEX with/without OCDA, so the owner of LoopringV3 doesn't have to monitor the price of LRC or Ether to update the configuration on a regular basis, thus making the protocol more decentralized.

- offchain: we can use the price provided by an oracle to trigger stop-limit orders to become limit-orders, especially during the early stage of launch when the trading price is more fluctuated due to low liquidity.

Loopring's onchain trading data (as function calldata) can also be parsed by any third party to create a price feed for oracles. The data are actually more trustworthy as it can be easily verified by another party. However, it is still expensive if not impossible to create SNARK-like proofs for such price feed as the OCDA is not designed for such purpose.

**Comment by Brechtpd** [comment]
The operator can easily manipulate the price inside the exchange itself by trading with himself at whatever price he wants. So enforcing this on the protocol level for each exchange independently seems impossible.

Using the price from an onchain price feed is also pretty difficult.

In circuit:
  - We'd have to get the prices of ALL tokens registered on the exchange inside the circuits like token/ETH  (probably by creating a Merkle tree for all these values)
  - We'd need to do this in snapshots every couple of minutes (probably longer), because these prices need to be known before the operator can start creating a block, so there will always be some delay on the prices
  - Calculate the tokenA/tokenB price by using tokenA/ETH and tokenB/ETH
  - Check if the stop price was reached

On-chain:
- We can also check e.g. the stop price completely onchain so we don't have to get the data in the circuits, which is expensive. We could add a flag to the OCDA that it's a stop order and only for these orders we'd do additional onchain logic that checks the price (which will be quite expensive). Note that we also need the snapshot/delay of prices in this case, otherwise the price may have changed between block creation and commitment onchain.

Doing it strictly on-chain seems to make more sense and keeps things simpler and is likely also cheaper (because the amount of stop orders will be limited).

Both cases still depend on the operator to actually execute the stop order though, so you still have to trust the operator for that (if an exchange has multiple operators that is a lot better because it will be much more difficult to censor the order). The onchain price check would be an additional safety for users.  But in the 1 operator/exchange case it's still useful I think.
