### ISSUE TITLE
[Protocol 3.1] Allow smart contract to open account and submit orders

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#704]
This can be done using https://eips.ethereum.org/EIPS/eip-1271

**Comment by Brechtpd** [comment]
For on-chain transactions users never have to sign anything because we just use `msg.sender`, which should work perfectly fine with smart wallets even in v3.0. So creating an account, depositing/withdrawing works as expected. For v3.1 this EIP could be one of a few possible authorization methods in the Agents when users may need to sign something for more complex on-chain transactions.

For off-chain requests users do have to sign something, so an on-chain alternative for signing requests off-chain with EdDSA seems like it could definitely be useful! A similar design as with conditional transfers can be used, where we would have e.g. an `approveOrder` function on the ring settlement module and the authorization is left to Agents so that the authorization itself can be done using any on-chain verifiable mechanism.

This will of course be much more expensive on-chain so this should only be used when signing requests with EdDSA is impossible, otherwise we would lose a lot of the scalability that v3 gives us. The cost is 350 gas/trade when the signature can be checked off-chain (which is just the calldata cost), compared to at least ~3000 gas/trade when we have to check the authorization on-chain. And these are just the gas costs for the operator, users would also have to pay ~40,000 gas/order for the authorization itself.
