### ISSUE TITLE
[hebao] support Multihash so more types of signatures can be supported

### ISSUE THREAD

**Issue by letsgoustc** [Loopring/protocols#780]
https://ethresear.ch/t/pragmatic-signature-aggregation-with-bls/2105
https://medium.com/cryptoadvance/bls-signatures-better-than-schnorr-5a7fe30ea716
https://electriccoin.co/blog/new-snark-curve/

As eth2 will use BLS instead of ECDSA for verify multiple signature, we can follow to use it in our multiple signature implementation.

**Comment by Brechtpd** [comment]
We should certainly make sure we can support multiple signature types (EIP-712 being the most important one right now I think).

Supporting BLS right now isn't really important I feel, maybe in 1-2 years when ETH2 is actually being used for smart contracts or when verifying BLS signatures gets substantially cheaper on ETH 1.X. BLS signatures are currently expensive to check on-chain (I don't have a good estimate, [this still has issues](https://github.com/kfichter/solidity-bls) and [SKALE (BLS-rollup) hasn't open sourced their smart contracts yet](https://github.com/skalenetwork/skale-network/blob/master/OPEN_SOURCE_PLAN.md) which would contain a good implementation. A rough estimate is that verifying a BLS signature costs 100,000 - 200,000 gas on Ethereum right now (which could do a bunch of signature verifications at once if the same data is hashed, which would be the case for us). Compared to ECDSA which costs 4,000 gas/signature, which has more flexibility for different weights/address and is supported in everything (hardware wallets/metamask/...). In most cases we'll also just check just a single signature because multiple signatures are only used for special operations which should be pretty rare.

**Comment by dong77** [comment]
Supporting more types of signing algorithms should be important, so the ABI should be designed to cope with other signing algorithms. Maybe we should still use [Multihash](https://github.com/Loopring/protocols/blob/master/packages/loopring_v2/contracts/lib/MultihashUtil.sol)  which supports EIP-712.

For multiple signature support (one tx with multiple signatures), the current ABI should be fine, such as this one:

```solidity
metaTxHash.verifySignatures(signers, signatures);
```

The `signatures` is a `bytes` so it should be *extensible*.

The current implementation of the `verifySignatures` method does have an issue. It assumes all signatures are 65 bytes and are ECDSA signatures. We should convert it to support Multihash and multiple signatures.

**Comment by dong77** [comment]
@Brechtpd @hosschao please take a look at https://github.com/Loopring/protocols/pull/782
