### ISSUE TITLE
[Loopring3] We need to finalize protocol parameters.

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocols#821]
## LoopringV3 和 ExchangeV3 参数设置：

Contract |Variable|Comment|Suggested Values (kongliang) |Suggested Values (daniel & brecht)
------------ | ------------- | --------------------------------- | ------------------ | ------------ |
LoopringV3 | exchangeCreationCostLRC | 创建一个交易所合约需要燃烧的LRC  | 100000  | 250,000 |  
LoopringV3 | maxWithdrawalFee | 交易所最高的提现费用(ETH) |  0.02 | 0.025 |  
LoopringV3 | tokenRegistrationFeeLRCBase | 交易所注册Token需要燃烧的基准LRC数目 |  2000  | 10,000 |  
LoopringV3 | tokenRegistrationFeeLRCDelta | 交易所注册Token需要燃烧的增量LRC | 100  | 500 |  
LoopringV3 | minExchangeStakeWithDataAvailability | 链上数据可用交易所最少需要抵押的LRC | 250000    | 500,000 |  
LoopringV3 | minExchangeStakeWithoutDataAvailability | 链上数据不可用交易所最少需要抵押的LRC |   5,000,000  |  |  
LoopringV3 | revertFineLRC | 执行回滚block操作需要燃烧的LRC  |  50000 | 5000 |  
LoopringV3 | withdrawalFineLRC | 交易所逾期及时使处理token提现，每个提现处罚的LRC数目 |  100  |  100|  
LoopringV3 | minProtocolTakerFeeBips | takeFeeBips最小值 |  25   | 25 |  
LoopringV3 | maxProtocolTakerFeeBips | takeFeeBips最大值 |   50  | 50 |  
LoopringV3 | minProtocolMakerFeeBips | makerFeeBips最小值 |  10   | 0 |  
LoopringV3 | maxProtocolMakerFeeBips | makerFeeBips最大值 |  25   | 25 |  
LoopringV3 | targetProtocolTakerFeeStake | takerFeeBips计算基准值 | 25000000 | 25000000 |  
LoopringV3 | targetProtocolMakerFeeStake | makerFeeBips计算基准值 | 10000000 | 25000000 |  
ExchangeV3 | accountCreationFeeETH |  新建账号费用  | 0.00001  | 0.01 |  
ExchangeV3 | accountUpdateFeeETH | 更新账号费用  |  0.00001  | 0.001 |  
ExchangeV3 | depositFeeETH | 充值费用 |  0.00001   | 0.001 |  
ExchangeV3 | withdrawalFeeETH | 提现费用 |  0.00001   | 0.002 |  
DowntimeCostCalculator | basePricePerMinute | 基础价格（每分钟）| 10 | |
DowntimeCostCalculator | maxPenalty | 最大罚金 | 100000 | |
DowntimeCostCalculator | gracePeriodsMinutes | 优惠时间 | 1440 | |
DowntimeCostCalculator | gracePeriodPricePerMinute | 优惠价格（每分钟）| 2 | |
DowntimeCostCalculator | maxAvailableDowntimeMinutes | 最大时间间隔 | 10000 | |

**Comment by letsgoustc** [comment]
minExchangeStakeWithDataAvailability抵押是不是要多一点，建议设置为50万LRC，revertFine是有点高，建议设置为5000，minProtocolMakerFeeBips是不是要考虑设为0，鼓励Maker挂单

**Comment by dong77** [comment]
这些是不是都是后续可以更改的？

**Comment by Brechtpd** [comment]
I think most values are fine, both suggested values of @kongliangzhong and @dong77. I would lean closer to the value of Daniel mostly. But some values I would change or eventually change:

- `revertFineLRC` should be higher, but as the initial value it's acceptable even at 5,000LRC. Eventually it should be >$[1,000; 10,000]  because it should not happen.

- `withdrawalFineLRC` is for each withdrawal so 100LRC is a good target, but for this initial release this can be much lower, [1, 10] LRC for example, because a user can always do the withdrawal himself if he's waiting on it.

- I take it the protocol fees given in the list use the format used in the protocol which is actually BIPS/10? So the max value of 255 for the protocol fees in the smart contracts is actually 0.255%, higher is not possible (but I would not know why we would charge such high protocol fees). If so than I think Daniel's values are good. Setting `minProtocolMakerFeeBips` to 0 with the current high `targetProtocolMakerFeeStake` seems like a good idea to me as well.

- `accountCreationFeeETH`, `accountUpdateFeeETH` and `depositFeeETH` should be as low as possible as these directly impact users. I would set `accountCreationFeeETH` and `accountUpdateFeeETH` to 0 as they don't have any proof generation cost. `depositFeeETH` perhaps should also be 0, at least for the initial release and we see that it isn't exploited (which it probably won't be because there are gas costs to do the deposit as well, so it's not free anyway). If it's not 0 than something close to the actual costs for the deposit, which should be something around 0.0001 ETH? There's no reason to make a profit on these, we need to get people to trade.

**Comment by dong77** [comment]
@Brechtpd please take a look at the protocol fee settings again. 
`maxProtocolMakerFeeBips` is set to `75 ` so it means 0.075%

**Comment by Brechtpd** [comment]
> `accountCreationFeeETH` needs to be non-zero to prevent Sybil attack for now.

We could do it with `IAddressWhitelist` and only allow people to sign up that way. If not, `depositFeeETH` is still charged + gas fees so it's not actually very cheap to do, but you're right that the costs will be pretty low.

**Comment by dong77** [comment]
@kongliangzhong please use the last column for now. These parameters can be adjusted later on. Just discuss the last 4 parameters with the Shenzhen team.

**Comment by dong77** [comment]
WeDEX will reimburse the account registration fee to whitelisted addresses, so the fee is mainly for prevent malicious sybil attackers.

**Comment by dong77** [comment]
@kongliangzhong I'll close this issue.
