### ISSUE TITLE
[hebao] remove `completeRecovery`

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#868]
@Brechtpd shall we remove the `completeRecovery` function and make the new owner takes effect after the waiting period automatically?

**Comment by dong77** [comment]
Same with the `confirmGuardianAddition` function. Should we also remove it as well.

**Comment by Brechtpd** [comment]
I would keep them because they make things more efficient and easier in normal cases. And these processes (especially recovery) will rarely be used anyway (though I understand that it's a bit more work on the UI side, though the UI could do this automatically as well by overcharging the user for the initial `addGuardian` meta transaction so the user still pays for it as well).

`completeRecovery`:
Here it is debatable and both options are pretty much the same, `completeRecovery` does make things easier (just a simple set function on the wallet itself which is nice and keeps the core wallet contract very simple, an event is emitted when the owner actually changes). Adding a check on time could add 1000 gas for each query (800 gas for an extra SLOAD + some extra gas for extra logic), but we should be able to work around that in most cases.

If you think it makes the UI better/easier (while making the smart contract a bit complexer) I think we should change it, otherwise I would keep the current mechanism. 

`confirmGuardianAddition`:
I think we should keep the current system here because we keep a list of guardians which will be harder with a time based system. Even for doing something simple like `numGuardians` we would have to run over all guardians to find out.
