### ISSUE TITLE
[hebao] possible duplicate wallet address

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#869]
Currently, the address of a new wallet is determined by the owner's address.
```solidity
       // Deploy the wallet address
        _wallet = Create2.deploy(
            getSalt(_owner),
            getWalletCode()
        );
```
Imagine an owner create an address, give the ownership to another address, then use the owner address to create another wallet,...

should we check the to-be-created wallet address doesn't exist already?

**Comment by Brechtpd** [comment]
`CREATE2` will fail if the contract is already deployed, so I don't think we need to worry about checking that. If the UI creates a new keypair for the owner it can assume the wallet can be created, if the owner address is not random the UI will have to check if the wallet has already been created.

> Imagine an owner create an address, give the ownership to another address, then use the owner address to create another wallet,...

This will try to create a wallet at the same address as the first smart wallet, so this will fail. If the owner really wants to use the same keypair for another wallet he can first generate a new public key for the same private key and then optionally transfer the ownership back to his first public key address. Another option would be to add a nonce or something like that to the salt, but that would be another piece of data the user would need to have to be able to create the wallet himself (this is important if the user deposits funds to the smart wallet before it is created). I think because the wallet owner will always be the keypair stored on the user's device in our case the owner keypair used for generating the wallet should always be newly generated anyway.
