### ISSUE TITLE
[Loopring 3.5] commit+verify as one single step

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#901]
This is Brecht's idea and I like it a lot. We should just have a `submitBlocks` operation which is a combination of `commitBlock` and `verifyBlock`. The `submitBlocks` operation should allow submitting blocks of multiple types and sizes.

It's debatable whether we should allow `revertBlock`. I prefer the flexibility of having it just in case. But this operation should really burn quite some LRC.

**Comment by Brechtpd** [comment]
A commit+verify function could easily be implemented in an operator contract (with only a very slight reduction in efficiency). So I don't think it's super necessary to do this in the exchange itself.

I think the bigger question is if we still want to support `revertBlock`, so if it's possible to commit blocks without immediately proving them.  Not supporting it makes on-chain interactions easier (as we don't have to support reverting them) and it could also save gas because we need to store less data on-chain.

On the other hand, it could also increase gas costs in certain scenario's if batching the proofs is harder as we would need to proof the blocks as they are committed immediately.

I think any gas costs savings are secondary to the main question:
- Not supporting independent commit and verify function makes it harder to support a decentralized operator setup (as proving a block can take a long time, so the data necessary for another operator to start building on the last proven block takes a while. An off-chain data sharing system would be necessary between operators to make this work well).
- Not supporting independent commit and verify function makes supporting revert unnecessary which makes things easier and makes certain things more efficient.
- Not supporting independent commit and verify function has slightly different finalization properties as just commit block now has economic finality which is fast compared to the actual finalization after verify (depending on prover times).

**Comment by dong77** [comment]
I think we still need to support the `revertBlock` operation, for example, if the operator didn't wait for enough deposit confirmations, he will need to revert a deposit block even if there is a fee for it. Not supporting `revertBlock` will make the DEX vulnerable to blockchain reorganization. 

I like batch-verification of SNARKs, the thing I'm not sure about is the amount of gas we can reduce if we simply commit+verify to one single operation, compared to the gas reduction from batch-verification.

If disabling independent commit and verify function can save a lot of gas, maybe we can give up supporting batch-verification and allow the operator to revert up to N blocks with a penalty.

**Comment by Brechtpd** [comment]
> I think we still need to support the `revertBlock` operation, for example, if the operator didn't wait for enough deposit confirmations, he will need to revert a deposit block even if there is a fee for it. Not supporting `revertBlock` will make the DEX vulnerable to blockchain reorganization.

Blockchain reorgs shouldn't be a problem. If the operator commits a block containing deposits we check on-chain if the deposit was indeed done on-chain. So with a reorg we can only have the following cases:
- A deposit was done by a user but it is reorged out. In this case the operator cannot commit a block using the deposit because it's not in the deposit queue any more when the block is committed.
- A deposit was done by user and the operator committed a block using the deposit. A reorg either only rolls back the block commit (in which case the block needs to be committed again) or rolls back the block commit + deposit (in which case the operator needs to create a new block using only deposits that are still in the deposit queue).

> I like batch-verification of SNARKs, the thing I'm not sure about is the amount of gas we can reduce if we simply commit+verify to one single operation, compared to the gas reduction from batch-verification.

The potential gas savings with batch verification (around 150,000 gas I think) are higher than the gas savings of merging commit+verify (around 40,000 gas probably). Withdrawals however could be a lot cheaper because we don't necessarily need to store the withdrawals on-chain (though the block size will be limited because we'd still need to keep the Ethereum block limit in mind for doing all the token transfers immediately). But the commit+verify function could also take multiple blocks and do batch verification when possible to still have (some) of the savings of batch verification, but with less flexibility so perhaps less optimal. Though the large majority of blocks will probably be trading blocks anyway so this may not have a big impact as batch verification will simply be possible in the majority of cases anyway even if blocks are handled sequentially for the batch verification.

> If disabling independent commit and verify function can save a lot of gas, maybe we can give up supporting batch-verification and allow the operator to revert up to N blocks with a penalty.

In any case if we remove independent commit and verify than we do not need to support reverts any more. Either the block submitted on-chain is valid or it is not valid (in which case the transaction submitting the block would fail).

I guess a lot of this depends on what we'll be able to do in v4. If we'll be able to create very large blocks batch verification isn't really important. The type of SNARK we use may not even be able to have more efficient batch verification.

**Comment by dong77** [comment]
I see. After digesting all your feedback, I would prefer disabling `revertBlock` and independent commit and verify and adding a `submitBlocks(...)` method to preserve batch verification of multiple proofs. I believe this will simplify our contract implementation.

**Comment by dong77** [comment]
see [[Loopring 3.5] Loopring 3.5 New Features and Changes ](https://github.com/Loopring/protocols/issues/1034)
